### ISSUE TITLE
Combined `All` file breaks compilation of subsets of packages

### ISSUE THREAD

**Issue by peterlefanulumsdaine** [UniMath/UniMath#1025]
The overall `Unimath/All.v` file added in #1015 breaks compilation of subsets of packages.  This showed up in the latest Travis build of UniMath/TypeTheory , https://travis-ci.org/UniMath/TypeTheory/builds/444476127 , where the build command

    make PACKAGES="Foundations MoreFoundations Combinatorics Algebra NumberSystems CategoryTheory Topology Ktheory"

for `UniMath` fails with error 

    make[2]: *** No rule to make target `UniMath/PAdics/All.vo', needed by `UniMath/All.vo'.  Stop.

So it seems it still tries to compile the combined `All` file, but that depends on the packages that haven’t been compiled.

I guess the least obtrusive fix would be to update the `Makefile` so that `UniMath/All.v` is not compiled when the `PACKAGES` variable is set non-trivially?

**Comment by peterlefanulumsdaine** [comment]
(closed and reopened due to accidental mis-clicking)

**Comment by benediktahrens** [comment]
Interesting! The file UniMath/All.v is made on the fly using the code
```
	for P in $(PACKAGES);							\
	do echo "Require Export UniMath.$$P.All.";				\
	done
```
but it seems that that code does  not work correctly, in that it does not take into account the overriding of the PACKAGES variable by the `make` command?

**Comment by DanGrayson** [comment]
Oops, and one thing I didn't consider when adding that, is that compiling UniMath/All.vo requires all the other packages to be compiled, but the whole reason we have travis subjobs is because it took more than 45 minutes to compile them all.

**Comment by DanGrayson** [comment]
Actually, the problem is that the file `UniMath/All.v` exists already in the repository and its
time stamp is recent, so it doesn't get remade, even if the value of `PACKAGES` is overridden
on the command line.  One solution would be to remove it from the repository, so that it
would get made on the fly, but then we aren't testing what we want to test: whether one can
load all our packages simultaneously.  That test requires making all the packages, which we used
to not be able to do under the travis time limit.  We could resign ourselves to just testing that
at home, when we run `make all` before submitting a pull request.

> Interesting! The file UniMath/All.v is made on the fly using the code
> 
> ```
> 	for P in $(PACKAGES);							\
> 	do echo "Require Export UniMath.$$P.All.";				\
> 	done
> ```
> but it seems that that code does not work correctly, in that it does not take into account the overriding of the PACKAGES variable by the `make` command?

**Comment by DanGrayson** [comment]
> On 24/10/2018 10:20, Daniel R. Grayson wrote: Actually, the problem is that the file |UniMath/All.v| exists already in the repository and its time stamp is recent, so it doesn't get remade, even if the value of |PACKAGES| is overridden on the command line. One solution would be to remove it from the repository, so that it would get made on the fly, but then we aren't testing what we want to test: whether one can load all our packages simultaneously.
> Can we have a separate make target for this test - one that the `all` target does not depend on?

Then no one would ever test it...

**Comment by DanGrayson** [comment]
Let's opt for this one:

" One solution would be to remove it from the repository, so that it would get made on the fly, but then we aren't testing what we want to test: whether one can load all our packages simultaneously."

Most of us build the whole repository before submitting a pull request, so we will be testing whether loading all of the files simultaneously works, even if travis doesn't do that for us.

If you agree, I can submit it..

**Comment by benediktahrens** [comment]
On 04/11/2018 07:40, Daniel R. Grayson wrote:
> Let's opt for this one:
> 
> " One solution would be to remove it from the repository, so that it 
> would get made on the fly, but then we aren't testing what we want to 
> test: whether one can load all our packages simultaneously."
> 
> Most of us build the whole repository before submitting a pull request, 
> so we will be testing whether loading all of the files simultaneously 
> works, even if travis doesn't do that for us.
> 
> If you agree, I can submit it..

Yes, that would be great.

**Comment by peterlefanulumsdaine** [comment]
I agree this seems a good solution for now, so that partial builds of UniMath aren’t broken.  But I’ve found the master `All.v` file extremely useful, since it allowed easy Coq searching of the whole library with `Search` / `SearchAbout` — useful lemmas often turn up in unexpected packages, and it made these much more discoverable.  So if one of us has the time to try to get a master `All.v` working in a `$PACKAGES`-aware way, as originally intended, that would be very nice to have!

(I will have a go at some point, though my Makefile-fu is rather weak so I’m not very confident of success.)

**Comment by DanGrayson** [comment]
The behavior you desire will be retained.  The only difference will be that All.v is created from scratch more often.
