### ISSUE TITLE
Unify names of builder functions

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#1096]
We have different ways to name builder functions, e.g., there are `makecategory` and `mk_precategory`. 
We should have one way, e.g., always use prefix `mk_`.

**Comment by DanGrayson** [comment]
Let's not implement a change to the code without first agreeing on what it should be.  It should be part of a comprehensive proposal about how identifiers should be named, as discussed in #687 and in #176.

**Comment by siddharthist** [comment]
Don't forget the the `*pair` names, like `weqpair` and `iscontrpair`.

I actually think that this can be done separately from a more comprehensive overhaul. If the builder/constructor names are consistent with one another, they will be easy to make consistent with whatever overall scheme we adopt (i.e. with a script).

To that end, I suggest a naming scheme for builders in particular following the `no_caps_with_underscores`, and beginning with `make_`. But I would prefer to see any uniformity adopted rather than bikeshed about which naming convention is best.

**Comment by benediktahrens** [comment]
+1 for `make_`
+1 for fixing this issue as soon as possible

**Comment by siddharthist** [comment]
The proposal here is also in line with what we've decided on #1215.

**Comment by arnoudvanderleer** [comment]
@benediktahrens Has this been fully resolved with Marco's PR?

**Comment by arnoudvanderleer** [comment]
For now I'll assume this has been resolved. If not, you may reopen it
