### ISSUE TITLE
Make separate package for Bicategories

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#1126]
CategoryTheory is the package with the longest compile time. It seems reasonable to split it into several (here: two).

**Comment by siddharthist** [comment]
Perhaps it would be even more useful to have more granular compile units than packages. Maybe each subdirectory could have its own 'make' rule? And we could just have a file describing how to split it up in CI.

This scheme would help us retain logical organization, rather than being forced to split things up for reasons of expediency.

**Comment by DanGrayson** [comment]
If they fix the bug I reported in #1046, the timings might improve dramatically.

**Comment by DanGrayson** [comment]
CategoryTheory takes only 13 minutes to check, which is much less than the 45 minute travis limit, so why split it up?

**Comment by benediktahrens** [comment]
This issue is solved, closing.
