### ISSUE TITLE
Constructors for sigma types with propositions

### ISSUE THREAD

**Issue by siddharthist** [UniMath/UniMath#1218]
Since propositions are proof irrelevant, proving them equal is trivial. Perhaps we should encourage users to have constructors of sigma types of the form `\Sigma x : A, B x` where `B x : hProp` to make their second components opaque using `abstract`? Are there any obvious downsides? (The upside would be smaller, more readable goals and proof terms)

**Comment by mortberg** [comment]
Propositions in HoTT/UF are **not** proof irrelevant. This is a very common misconception. Consider `weq X Y`. The second component is `isweq f`, it is a proposition, but if you make it opaque then you cannot invert the function `f`!

However, it is very often the case that the content of propositions are never used for anything and that they can be made opaque (for example equations in algebraic and categorical structures). I have made some more clever constructor functions for this in certain cases, like: 

https://github.com/UniMath/UniMath/blob/master/UniMath/CategoryTheory/Core/Functors.v#L97

It might be a good idea to always do this for all categorical structures. This way one knows that if one uses the `mk_` functions then the prop part is always opaque and if one wants it to not be opaque then one can write `use tpair` instead.

**Comment by rmatthes** [comment]
@mortberg: I am sorry to say that, but it seems that your device with `abstract` in the definition of `mk_functor` does not work. I looked at `induced_precategory_incl` in `NaturalTransformations.v`. This uses `mk_functor`, but when printing the definition, all is still there. When enclosing `repeat split` in that definition by `abstract`, then the structure gets really smaller, by using `induced_precategory_incl_subproof` whose full definition can be printed but which will not be evaluated with `Eval compute in induced_precategory_incl.` This latter command on the library def. evaluates to a term with a `mk_functor_subproof` that gets the whole proof one would have liked to hide as argument!

**Comment by DanGrayson** [comment]
> Propositions in HoTT/UF are **not** proof irrelevant. This is a very common misconception. Consider `weq X Y`. The second component is `isweq f`, it is a proposition, but if you make it opaque then you cannot invert the function `f`!

That depends on what you mean by "cannot".  You can invert it, but you cannot compute the inverse.

**Comment by siddharthist** [comment]
@mortberg Thanks for clarifying the issue. I guess there are two questions:

 1. Can we classify those propositions with proofs that should be made opaque?
 2. (As raised by @rmatthes) Do we have techniques for reliably making them opaque in constructors?

**Comment by mortberg** [comment]
> That depends on what you mean by "cannot". You can invert it, but you cannot compute the inverse.

Indeed, I was thinking of computing the inverse. No matter what my point that propositions in HoTT/UF are proof relevant stands.

**Comment by mortberg** [comment]
> @mortberg Thanks for clarifying the issue. I guess there are two questions:
> 
>     1. Can we classify those propositions with proofs that should be made opaque?
> 
>     2. (As raised by @rmatthes) Do we have techniques for reliably making them opaque in constructors?

1. This is a subtle problem. Various people have worked on adding a universe of strict propositions (where all of the inhabitants of a proposition are definitionally equal) to type theory, maybe this could be part of UniMath one day. But until then I think we just have to rely on heuristic arguments for why a particular proof of a proposition can be made opaque. 

2. Not really... My `mk_` trick using abstract is **not** working. So we should remove all of them in order not to confuse people. We could imagine doing some Ltac hacking or using ssreflect style locking to prevent Coq from comparing subterms, but that is not very elegant. Maybe the best is just to make sure that everyone is careful about this and follow the recommendation to always make the operations transparent but the properties opaque when instantiating categorical/algebraic structures.

**Comment by DanGrayson** [comment]
Re: "my point ... still stands."

Well, still, your statement "propositions in HoTT/UF are not proof irrelevant" requires some repair.  One definition of "proposition" in HoTT is that they are the proof-irrelevant types.

**Comment by mortberg** [comment]
> Re: "my point ... still stands."
> 
> Well, still, your statement "propositions in HoTT/UF are not proof irrelevant" requires some repair. One definition of "proposition" in HoTT is that they are the proof-irrelevant types.

Haha, this is getting funny. I think we are using the word "irrelevant" differently. My example shows that proofs of propositions in HoTT/UF are relevant as they allow us to do things that we couldn't do if we erased them. Can you explain what you mean by "irrelevant"?

To clarify by "proposition" I mean an inhabitant of hProp.

**Comment by DanGrayson** [comment]
A type is called "proof-irrelevant" if any two of its elements are equal.  Here is a definition in UniMath:
```
Definition isProofIrrelevant (X:UU) := ∏ x y:X, x = y.
```

**Comment by DanGrayson** [comment]
... and we have these facts:
```
Lemma isaprop_isProofIrrelevant X : isaprop (isProofIrrelevant X).
Lemma proofirrelevance (X : UU) : isaprop X -> isProofIrrelevant X.
Lemma invproofirrelevance (X : UU) : isProofIrrelevant X -> isaprop X.
```

**Comment by jonsterling** [comment]
Hi Dan, that is not what "proof irrelevance" means; this is actually the essence of the difficulty, since proof irrelevance of a type is a meta-property which cannot be expressed in terms of the language of UF --- in particular, proof irrelevance is _not_ stable under isomorphism.

**Comment by DanGrayson** [comment]
Okay, what's your definition?

**Comment by mortberg** [comment]
> A type is called "proof-irrelevant" if any two of its elements are equal. Here is a definition in UniMath:
> 
> ```
> Definition isProofIrrelevant (X:UU) := ∏ x y:X, x = y.
> ```

Ah, I see what the confusion is. By "proof irrelevant" I mean types where "the proof is irrelevant". That is not the same as having the same inhabitants up to a path, it's not even the same as having all inhabitants be definitionally/judgmentally equal.

**Comment by DanGrayson** [comment]
re: "By "proof irrelevant" I mean types where "the proof is irrelevant". "

And what do you mean by "the proof is irrelevant"?

**Comment by siddharthist** [comment]
Since we have no good way to distinguish which propositions should have opaque proofs, nor a way to systematically make said proofs opaque, I'm going to close this issue. Feel free to keep discussing, obviously.

**Comment by jonsterling** [comment]
@DanGrayson Historically, "proof irrelevance" has meant something like "All elements of the type are exactly equal"; in the case of the semantics of UF, one would consider the simplicial sets `F` whose fibers `F(Delta[n])` are having exactly one element, up to set-theoretic equality.

The use of the word "irrelevance" for this kind of thing comes from computer science, where people were interested in considering types whose elements could be "compiled away" / deleted when a proof is converted into an algorithm or computer program. The h-propositions in UF do not have this property, since if you erase their elements, your programs won't run.

**Comment by mortberg** [comment]
> re: "By "proof irrelevant" I mean types where "the proof is irrelevant". "
> 
> And what do you mean by "the proof is irrelevant"?

If making the proof opaque it doesn't affect anything. In other words we can erase or forget about the proofs. As is the case for inhabitant of propositions in Prop in Coq.

**Comment by DanGrayson** [comment]
Re: "If making the proof opaque doesn't affect anything."

Erasing the proof *always* affects something, namely, the computation of the proof.  So that's not much of a definition.

Re: " "proof irrelevance" has meant something like "All elements of the type are exactly equal""

Okay, what does "exactly equal" mean?

**Comment by jonsterling** [comment]
> Re: " "proof irrelevance" has meant something like "All elements of the type are exactly equal""

@DanGrayson This depends a bit on the system one is considering, but a reasonable first approximation from a type-theoretic point of view is "all elements are judgmental equal". One way to test this in type theory is to see if the judgment `x : A, y : A |- x == y : A` holds. But I am trying to be a bit cautious, because this judgment might fail in the type theory and yet one might call the type `A` "proof-irrelevant" if this judgment holds in whatever you consider to be the "standard model" of the type theory --- for instance, sets or simplicial sets. Computer scientists on the other hand might check if this judgment holds in a computational model of the type theory, which they use to extract programs from proofs.

**Comment by DanGrayson** [comment]
Re: "**This depends a bit on the system one is considering, but a reasonable first approximation from a type-theoretic point of view is "all elements are judgmental equal"."

Are there any examples in UniMath?  I can't think of one.

**Comment by jonsterling** [comment]
@DanGrayson Coq doesn't have enough `eta`-laws to make this happen very often; other type theories, which are compatible with UF but are different from Coq, have enough equations to make this happen pretty often. In some type theories, one also considers "proof irrelevance modalities" which force all their elements to be judgmentally equal; for instance, Agda has support for this now. Anyway, this is usually what is meant by proof irrelevance, and it doesn't really occur in Coq or UF proper (but it might occur in some formal system which is compatible with UF).

**Comment by DanGrayson** [comment]
Maybe for clarity one should distinguish propositional proof irrelevance from judgmental proof irrelevance.  Then Anders can avoid confusion by pronouncing that in UniMath no types are judgmentally proof irrelevant.

**Comment by jonsterling** [comment]
One should certainly make the distinction, but it still doesn't resolve the problem with talking about 'proof irrelevance' of any kind in UF. The intuitions that come from any use of the phrase "proof irrelevance", even if qualified by "propositional", are odious and lead one to form misconceptions about how h-propositions work in univalent foundations (such as the misconception which prompted the idea of making abstract the second component of sigma types, in case the family is hprop-valued). I think it is better to just ban the phrase.

**Comment by siddharthist** [comment]
@jonsterling Thanks for your detailed explanations!

**Comment by DanGrayson** [comment]
Admittedly, one must be careful with the phrase, but why is the corresponding intuition "odious"?  The background in traditional math is clear: one may read a typical research paper by checking the proofs as one reads them, without referring to them again (unless the author explicitly refers to the proof).  Proofs of theorems in research papers are irrelevant, and mathematicians realize that.

The corresponding notion, when formalizing proofs, is one Anders tried to get at: suppose we say that a proof in a body of formalized proofs in Coq is "irrelevant" for the sequel if one may end it with `Qed` without preventing Coq from checking the remaining proofs.  A proof of a proposition may not be irrelevant for the sequel, as has been remarked, so there is indeed a gap between the notions of a "propositionally proof irrelevant type" and "a type with proofs irrelevant for the sequel".  

It might be too late for us to ban the phrase in UniMath, since it has been used from the beginning -- what would be a good substitute phrase for the concept in this definition?:
```
Definition isProofIrrelevant (X:UU) := ∏ x y:X, x = y.
```

**Comment by martinescardo** [comment]
Maybe "isSubsingleton" or "hasAtMostOneElement"?

**Comment by mortberg** [comment]
> It might be too late for us to ban the phrase in UniMath, since it has been used from the beginning -- what would be a good substitute phrase for the concept in this definition?:
> 
> ```
> Definition isProofIrrelevant (X:UU) := ∏ x y:X, x = y.
> ```

It doesn't seem to have been there from the beginning, it is not in: https://github.com/UniMath/Foundations

If I run `git blame` on PartB I get: 
```
36b46c29e UniMath/Foundations/PartB.v             (Daniel R. Grayson          2017-02-19 08:06:32 -0500  606) Definition isProofIrrelevant (X:UU) := ∏ x y:X, x = y.
```

So it seems like you added it only a few years ago?

We could call is `ishprop` for "is homotopy proposition" ?

**Comment by DanGrayson** [comment]
Here it is, from the beginning:
```
https://github.com/UniMath/Foundations/blob/df19211f602ab71ee44f0ae4de2a19170c5b9e4d/Generalities/uu0.v#L1931
```

**Comment by DanGrayson** [comment]
If forced to choose between "isSubsingleton" and "hasAtMostOneElement", I would choose the second one, because its meaning is immediately clear to mathematicians.

**Comment by mortberg** [comment]
> Here it is, from the beginning:
> 
> https://github.com/UniMath/Foundations/blob/df19211f602ab71ee44f0ae4de2a19170c5b9e4d/Generalities/uu0.v#L1931

Oops, my bad. So you probably just changed the name to use camelCase... I guess we have tracked down the source of the whole confusion then.

**Comment by DanGrayson** [comment]
We would need good names for these, too:
```
Lemma proofirrelevance (X : UU) : isaprop X -> isProofIrrelevant X.
Lemma invproofirrelevance (X : UU) : isProofIrrelevant X -> isaprop X.
```
These seem too long: `PropositionsHaveAtMostOneElement` and `TypesWithAtMostOneElementArePropositions`.

**Comment by DanGrayson** [comment]
No, actually, I introduced `isProofIrrelevant` so the concept would have a definition encapsulating it.  The names `proofirrelevance` and `invproofirrelevance` have been unchanged.  Those two lemmas used to look like this:
```
Lemma proofirrelevance ( X : UU ) ( is : isaprop X ) : forall x x' : X , paths x x' . 
Lemma invproofirrelevance ( X : UU ) ( ee : forall x x' : X , paths x x' ) : isaprop X.
```

**Comment by martinescardo** [comment]
Another possible one is "isTruthValue".

**Comment by mortberg** [comment]
Let me elaborate a bit on my answers yesterday by distinguishing 4 classes of propositions:

1. **Erasable** propositions that can be erased *after* typechecking without affecting computations.
2. **Irrelevant** propositions that can be erased *before* typechecking without affecting well-typedness.
3. **Strict** propositions where all elements are definitionally/judgmentally equal.
4. **Homotopy** propositions where all elements are related by a path/equality.

Examples of 1 are things like the accessibility predicates in Coq (https://coq.inria.fr/library/Coq.Init.Wf.html) that are used to prove the termination of algorithms by well-founded induction. 

Examples of 2 are any proposition that can be made opaque using `Qed` without affecting well-typedness. 

Examples of 3 and 4 we all know. 

It is useful to distinguish these classes and conflating them is confusing at best and misleading at worst. Many people from CS think of proof irrelevance in the strong sense of 2, so when they hear us say that "homotopy propositions are proof irrelevant" they think that we can always opacify them. I've met a lot of people who thought this was the case and they always have an "aha!" moment when I explain the `isweq` example to them. Because of this I like to emphasize that homotopy propositions are **proof relevant** and this is what makes them different from other notions of "proposition" considered in math/logic/CS.

**Comment by DanGrayson** [comment]
I like the clarity of the list, but I don't see how any proposition can ever be erasable, as I remarked before.  Given a proof of `Lemma p:P.`, one can always try to compute `p` itself.

The notion of "strict proposition" seems to be useless, at least in UniMath, since there are none.

**Comment by mortberg** [comment]
> I like the clarity of the list, but I don't see how any proposition can ever be erasable, as I remarked before. Given a proof of `Lemma p:P.`, one can always try to compute `p` itself.

Consider the problem of computing the Smith normal form of an integer valued matrix (diagonal matrix where the diagonal is ordered wrt divisibility). This algorithm is not structurally recursive but based on well-founded recursion using the fact that divisibility in the integers is a well-founded relation. Algebraically this corresponds to the fact that Z is a PID and hence Noetherian and satisfy the ascending chain condition. In type theory we can formulate this conveniently using the accesibility predicates that I linked to above. In Coq this is a `Prop` valued relation and I can use this to define a function for computing the SNF of any matrix. Now let's say I want to compile/extract my algorithm to OCaml in order to run it efficiently. As we only added the accessibility predicates to convince Coq that the algorithm terminates we should not have to compute them when computing the SNF of a matrix, so these propositions can safely be erased before running the algorithm.

**Comment by DanGrayson** [comment]
Yes, but your entire remark amounts to saying that *some* computations can, with care, be completed.  But erasability, as defined by you, seems to demand that *all* computations yield the same answer.  What about computing `p`?

**Comment by mortberg** [comment]
> The notion of "strict proposition" seems to be useless, at least in UniMath, since there are none.

If we define unit as a record then it would be an example of a strict proposition (the problem now is that we do not have a definitional eta principle for it). 

There is a recent paper that discusses how to add a universe of strict propositions to Coq in a way that is compatible with HoTT/UF: https://hal.inria.fr/hal-01859964v2/document

It contains many more examples and it might be interesting to use this in UniMath. I remember Vladimir telling me that he really wanted this. I don't remember exactly why, but I believe it might have been for set quotients.

**Comment by DanGrayson** [comment]
Re: "If we define unit as a record then it would be an example of a strict proposition (the problem now is that we do not have a definitional eta principle for it)."

You seem to contradict yourself.  I tried it in Coq yesterday and it doesn't work.

**Comment by mortberg** [comment]
> Yes, but your entire remark amounts to saying that _some_ computations can, with care, be completed. But erasability, as defined by you, seems to demand that _all_ computations yield the same answer. What about computing `p`?

Right, if you're interested in computing the proof of the accessibility predicate itself then you can of course not erase it. :-)

So I guess the notion of erasable proposition should be taken with respect to a specific algorithm. Anyway, this whole discussion was about irrelevant propositions.

**Comment by mortberg** [comment]
> You seem to contradict yourself. I tried it in Coq yesterday and it doesn't work.

Oh I didn't try this myself, maybe it doesn't work currently in Coq. So let's just say that if Coq would have definitional eta for Inductive's with one constructor then unit would be an example.
