### ISSUE TITLE
Identifier "subtypeEquality" should be renamed

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#1244]
"subtypeEquality" is a map on paths, not on equalities.

It should be renamed - e.g., to "subtypePaths"?

@DanGrayson : could you take care of this?

**Comment by DanGrayson** [comment]
My definition of "equality" is "path".   What is yours?

**Comment by benediktahrens** [comment]
On 27/06/2019 12:43, Daniel R. Grayson wrote:
> My definition of "equality" is "path". What is yours?
> 

One adequate use for "equality" would be for paths in a set, i.e., for 
paths that are essentially unique.
One could also make a case for avoiding that word entirely when working 
in uf, and reserve it, e.g., for judgmental equality.

General paths should not be called equalities; Vladimir chose the word 
"paths" for the identity type to emphasize that

I think the use of "equality" in this particular case is very misleading.

**Comment by DanGrayson** [comment]
I think there's a big advantage to letting mathematicians continue to use traditional terminology, such as "equality" and "equation", slightly tweaked to accommodate the new foundations.  Otherwise we run the risk of having the field appear sterile and divorced from tradition, with a heavy burden imposed on new participants.

I like the way I was permitted to put it in the symmetry book:
<img width="671" alt="Screen Shot 2019-06-27 at 2 35 07 PM" src="https://user-images.githubusercontent.com/700228/60291561-20680280-98e9-11e9-9d95-72d4c3ab6e31.png">

**Comment by martinescardo** [comment]
I agree with this. In my MGS notes I have been very careful (consciously) to use "identification" when it is important to emphasize that equality is not a truth value, but "equality" when this gives a more natural mathematical prose *and* there is no ambiguity.

**Comment by martinescardo** [comment]
As a remark, for pedagogical purposes, I avoid homotopy-theory terminology, not because I am against it (in fact I like the terminology), but because I want to emphasize that expertise in homotopy theory is not a prerequisite to understand univalent mathematics. In fact, the other way round may be true for some people: knowing univalent mathematics will help to understand homotopy theory. And for a select group of people, it works both ways round.

**Comment by martinescardo** [comment]
And, given we are at it, one more remark. I also consciously avoid the terminology "proposition" at all costs. For several reasons. One of them is propositions-as-types. But this is not the main one. I once read Tim Gowers saying that propositions are meta-mathematical objects. From then on, I stuck to "subsingleton", which any mathematician will understand as a mathematical object without further explanation.

**Comment by DanGrayson** [comment]
I would never have understood "subsingleton" without explanation, and I'm a mathematician.  And I think that the great thing about propositions is that they are now mathematical objects, so I relish being able to use the word in this new way. Similarly for proofs, which are now also mathematical objects.

**Comment by martinescardo** [comment]
Still the word "proposition" creates endless misunderstandings in this subject. Even for Coq users who are not mathematicians. This happened, for instance, in the last UniMath school, by a (clever, well established) researcher asking why we should have to prove that something is a proposition, rather than having them as a sort as in e.g Coq.

**Comment by DanGrayson** [comment]
Well, sure, there will be questions like that, but they are good questions about choices made when constructing the formalism that are easily answered.  How could they lead to "endless misunderstandings"?

**Comment by martinescardo** [comment]
Because people already have meanings for certain words that occur often in logic and mathematics in their heads, such as "proposition", which are radically different from the proposed new meanings. The same goes for "equality".

**Comment by DanGrayson** [comment]
When you said "I agree with this", what was "this"?

**Comment by martinescardo** [comment]
Using "equality" cautiously, but then identification when the identity type is used not quite like equality.

**Comment by martinescardo** [comment]
I do this for "proposition" too, with "subsingleton" when I want to emphasize that I am talking about a type that has at most one element, or that is a subtype of a singleton.

**Comment by DanGrayson** [comment]
You seem to contradict yourself.  First you said you are sticking to "subsingleton", and now you say you are using "proposition" sometimes.

**Comment by martinescardo** [comment]
You can check how I use the terminology in the lecture notes. I explain myself there when I contradict myself, usually blaming tradition. Search for "tradition" and you will see. :-)

**Comment by DanGrayson** [comment]
Tradition is a powerful force.   I think it's best to take advantage of it, not to buck it.

**Comment by martinescardo** [comment]
Tradition says that

   * Propositions are syntactical or meta-mathematical statements (logic).
   * Assertions (philosophy) which may or may not be true.
   * Types (Curry Howard)
   * Some types (Univalent mathematics)
   * subobjects of the terminal object (1-topos theory), collected in the subobject classifier.
   * Elements of a certain type (Coq)

How can I guarantee that when I am speaking, my interlocutor will attach the second last meaning among the other ones, given that univalent mathematics is an unknown subject to the majority of mathematicians, logicians, computer scientists and philosophers?

**Comment by martinescardo** [comment]
The case of equality is not quite the same. In univalent mathematics we expand our universe of discourse to go beyond sets. For sets, equality behaves in the same way. It is only for the new things that equality behaves in a different way, and this is precisely what defines the new things. So one is not chaning the notion of equality. One is generalizing it, without distorting it for the old, good, sets.

**Comment by benediktahrens** [comment]
On 27/06/2019 19:38, Daniel R. Grayson wrote:
> I think there's a big advantage to letting mathematicians continue to 
> use traditional terminology, such as "equality" and "equation", slightly 
> tweaked to accommodate the new foundations. Otherwise we run the risk of 
> having the field appear sterile and divorced from tradition, with a 
> heavy burden imposed on new participants.

In Vladimir's intended semantics - the simplicial set model - identities 
translate to paths, not to equalities. That's why he chose the name 
"paths" for this type.

**Comment by maggesi** [comment]
I favor Benedikt's proposal.
For better or worse, the term "path" is consistently used in the library (especially in the Foundations).

In my opinion, consistency has a high value (even when it is not entirely satisfying from a more high-level or philosophical point of view), because it helps people to learn and use the library.

While we are there, I would suggest avoiding the use of camel case for the same reason.
For instance, one should be able to find this theorem with the command
```
Search "sub" "path".
```

**Comment by DanGrayson** [comment]
About camel case: uniformity is good, but it's an open question what the uniform convention should be, as the discussion in https://github.com/UniMath/UniMath/issues/687 continues.

**Comment by DanGrayson** [comment]
Okay, I'm convinced, will do.
