### ISSUE TITLE
Coconus

### ISSUE THREAD

**Issue by nyraghu** [UniMath/UniMath#136]
uu0a.v says, "Coconuses: spaces of paths which begin (coconusfromt) or end (coconustot) at a given point" .  Why are these types called "coconuses"? Something to do with cocones?

In general, it'd be great to have a small comment explaining the etymology/motivation/purpose of each definition and theorem.  I understand it's a lot of work, and teaching isn't necessarily an aim of the UniMath library, but it'd be a tremendous help to people trying to learn about it.

**Comment by vladimirias** [comment]
Hi,

this a name that I introduce and it is indeed a variant of the name cocone. In Russian cone is written conus and correspondingly cocone is written coconus. This should be changed maybe with a comment left that it used to be called coconus.

Vladimir.

**Comment by DanGrayson** [comment]
Why is it "coconus" and not simply "conus"?  (I just now noticed that
"conus"
without the prefix is unused.)

**Comment by vladimirias** [comment]
Because it is cocone not cone. “Cone” is obtained by taking a colimit while cocone by taking a limit. Cones are not available in Coq.  They would be higher inductive types. A cone of f:X -> Y is

{ v : cone f ; i : forall y : Y, cone f ; ip : forall x : X , paths v ( f x ) }

(in my own old syntax for HITs)

**Comment by DanGrayson** [comment]
Thanks for the explanation.

**Comment by nyraghu** [comment]
> Because it is cocone not cone. “Cone” is obtained by taking a colimit while cocone by taking a limit.

Thanks here too!

**Comment by nyraghu** [comment]
I wonder if there is still a possibility of confusion, because a limit  is often defined as a [universal cone](http://ncatlab.org/nlab/show/limit#definition_in_terms_of_universal_cones), so a coconus is a cone in that sense.

**Comment by DanGrayson** [comment]
Indeed, my first thought in this connection was that a limit is a universal
cone and a colimit would then be a universal cocone.

**Comment by nyraghu** [comment]
Perhaps the confusing terminology here arises from the fact that the cone of a topological space is a pushout, and hence a universal **cocone**.  Maybe, one can get out of this by calling coconusfromt something like pathsfrompt, which indicates the space of paths from a point.

Does the t in coconusfromt refer to the argument t?  If so, it is perhaps better to remove it from the name, because it looks odd if one calls that argument x instead of t.

**Comment by DanGrayson** [comment]
Sensible suggestions.

**Comment by vladimirias** [comment]
The notion of a cone is well defined in topology. So is the notion of a cocone although the latter is less well known. Please do not bring unnecessary confusion to the discussion.

**Comment by vladimirias** [comment]
I agree. pathsfrompt and pathstopt are good names.

**Comment by nyraghu** [comment]
My apologies for bringing in confusion.

I have another comment on the coconus part of uu0a.v.  In Lemma connectedcoconustot, the inhabitedness of the type forall (c1 c2 : coconustot T t) is called the connectedness of the coconus.  On the other hand, in Lemma proofirrelevancecontr, the inhabitedness of the type forall (x x' : X), x = x' is called the proof irrelevance of X.  It'd perhaps be better if a single terminology is chosen for the inhabitedness of the type forall (x y : A), x = y.

**Comment by vladimirias** [comment]
Do you want to give a name to the expression forall ( x y : T ) , x = y ? I now call it “no parts” i.e.

noparts(T)=forall(x y : T), x=y.

Then one would have nopartscoconeto instead of connectedcoconustot

(if we also apply coconus -> cocone and tot -> to and fromt -> from)

The name proofirrelevant was used to emphasize the connection with the usual concept of proof irrelevance.

Many of these names have been chosen at the time when the code was written for reasons that were relevant at that particular moment.

I am not sure that we should invest time in changing these names now.

If you have a good idea on how to organize terminology of a particular set of concepts you can implement it  by creating a file with notations that will, without changing the original names, introduce new names.

Vladimir.

**Comment by nyraghu** [comment]
> I am not sure that we should invest time in changing these names now.

I agree.  There's no point in spending time on changing the names.

**Comment by DanGrayson** [comment]
Consensus reached, apparently, closing the issue.
