### ISSUE TITLE
CategoryTheory package depends on Bicategories

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#1396]
@rmatthes has introduced a dependency of package CategoryTheory on (some files of) the package Bicategories.

While I agree that it is conceptually undesirable to separate the two, this dependency means that Bicategories has to be compiled in other projects, at least in the CI.

How about the following suggestion: move the definition of bicategory, as well as a few other files (in particular, the bicategory of (univalent) categories), into the CategoryTheory package?

@rmatthes : what do you think? How many files would be moved? (Of course, a lot of Import statements would need to be changed - hopefully that could be automated.)

**Comment by rmatthes** [comment]
I have not yet thought about the global implications, but I would like to add an aspect to this issue: the instantiation of the concept of bicategory with CAT should not create new data but only take lemmas one could also use without the bicategorical infrastructure. So, the fields of the definition of CAT should all be lemmas that are readily available outside. And this probably even when the definition of bicategories is moved into the package CategoryTheory.

The packages CategoryTheory, Bicategories AND SubstitutionSystems are now intertwined because of file [ActionBasedStrengthOnHomsInBicat.v](https://github.com/UniMath/UniMath/blob/master/UniMath/CategoryTheory/Monoidal/ActionBasedStrengthOnHomsInBicat.v).

**Comment by rmatthes** [comment]
It is even worse: CategoryTheory depends on SubstitutionSystems as well. (A) CategoryTheory/Monoidal/ActionBasedStrengthOnHomsInBicat.v should be moved into SubstitutionSystems. (B) CategoryTheory/Monoidal/ActionsFormBicategory.v should be moved into Bicategories/DisplayedBicats/Examples, but the documentation of action-based strength should point to that further result at a distant place. (C) Bicategories/Core/Examples/BicatOfCatsWithoutUnivalence.v should go into CategoryTheory with a telling name such as CAT.v and a telling name such as CAT for the main construction. (D) CAT should receive sufficient attention in the library - see PR #1397. (E) Bicategories/Core/BicategoryLaws.v should go into CategoryTheory along with Bicategories/Core/Bicat.v, and these laws should be spelt out in the situation of CAT as well (as far as that is interesting), which is intimately related to my point above that CAT should be created with decent lemmas beforehand - call this point (F).

I hope I did not overlook other unwanted dependencies. There is certainly a lot of interference with PR #1391.

**Comment by benediktahrens** [comment]
Thanks a lot for this analysis, this is great! Would you consider the layout you are sketching to be reasonable? Would it allow for easy use of all the results in further development?

This issue does not need to be solved immediately. In particular, we should merge PR #1391 before working on this restructuring (if we decide to do it).

**Comment by peterlefanulumsdaine** [comment]
Thanks both for noting and recording this.  Like @benediktahrens , I think it would be good to untangle this dependency if possible: `CategoryTheory` is required for several other developments that don’t otherwise need `Bicategories` or `SubstitutionSystems`, and some of the files in these latter two are very slow to compile.

Has anyone started working on this yet?

If not: Besides the solution @benediktahrens suggests above (moving a few core files from `Bicategories` into `Categories`), another option would be to split up one or both packages into a “core” and a “further” part (or some such similar naming), with dependency order something like `Categories-core`, `Bicategories-core`, `Categories-further`, `Bicategories-further`.  Another possible naming convention: `Categories-1`, `Categories-2`, etc — which would more easily be further extensible in future.

**Comment by benediktahrens** [comment]
> Has anyone started working on this yet?

Not to my knowledge. 
@rmatthes is currently formalizing some material for the final version of a paper at CPP 2022 that is about monoidal categories and bicategories. He will thus touch on exactly the problematic material. For this reason, it would be great to postpone any actual work on this issue until @rmatthes 's work is done. There might be some planning to do first, anyway.

> If not: Besides the solution @benediktahrens suggests above (moving a few core files from `Bicategories` into `Categories`), another option would be to split up one or both packages into a “core” and a “further” part (or some such similar naming), with dependency order something like `Categories-core`, `Bicategories-core`, `Categories-further`, `Bicategories-further`. Another possible naming convention: `Categories-1`, `Categories-2`, etc — which would more easily be further extensible in future.

I like the idea of splitting the packages `CategoryTheory` and `Bicategories` into smaller ones. The appeal of using numbers to name them is undeniable. However, names guided by content would be helpful, especially since we are not so good at keeping Readme files up-to-date. (The situation seems similar to de Bruijn vs nominal variables.)

Possibly a first step would be to make a list of topics covered in both packages and draw a dependency graph between them. Or better, two dependency graphs - one that reflects the current status and one that projects desired dependencies. (For instance, the discussion of functor categories does not currently depend on bicategories, but could depend on them.)

**Comment by benediktahrens** [comment]
@rmatthes @peterlefanulumsdaine : It would be good to solve this issue soon. There might be a new version of the Coq Platform coming out, and with the recent growth of the `Bicategories` package, this package might need to be dropped from the Platform version. I would very much appreciate any input that you might have.

**Comment by peterlefanulumsdaine** [comment]
I’d be very happy to work on splitting this up; I can look at @rmatthes’ WIP branch and try to make sure to keep changes compatible with that, if @rmatthes is happy with that approach?

**Comment by rmatthes** [comment]
My [PR1397](https://github.com/UniMath/UniMath/pull/1397) received a comment by @benediktahrens on October 7, 2021, essentially saying that developments should be considered incomplete if univalence of the constructed categories is not established. Hence, there may only be little benefit from extending the results on the bicategory of categories with homsets but not necessarily univalence. But the situation is not as clear-cut as with precategories that have been mostly wiped off from the UniMath library with [PR1402](https://github.com/UniMath/UniMath/pull/1402). The idea there was that maximum generality of statements (not requiring homsets) did not good service to the library. However, it seemed good to formulate results that do not depend on univalence, even if all categorical constructions ought to come with univalence proofs. This should be particularly true for the basic use of bicategory concepts, applied to the categories. But this view could lead to code duplication.
At the time of preparing PR1397, I felt the need for more bicategorical results for functors and natural transformations much stronger than now, since [PR1424](https://github.com/UniMath/UniMath/pull/1424) avoided the need for those bicategorical results by just generalizing to bicategories the results that had been problematic to prove. The moral there was: if reasoning with functors and natural transformations becomes very bicategorical, then maybe there is a general bicategorical result to be found where the reasoning is then just natural.

I am fine with @peterlefanulumsdaine.

**Comment by DanGrayson** [comment]
By the way, I'm looking forward to thinking about applying the standard combinatorial constructions of the higher algebraic K-groups to univalent categories, such as the category of finitely generated projective modules over a ring R.  It will require handling simplicial types, in some sense, and defining the geometric realization of such a thing.
