### ISSUE TITLE
Request for a reference

### ISSUE THREAD

**Issue by nyraghu** [UniMath/UniMath#144]
Is there a book on homotopy theory or model categories that'd be good to keep in mind when reading the material on homotopy fibre triangles, fibration sequences, etc., in uu0a.v?

**Comment by vladimirias** [comment]
Most of it is new research by me, V.V. that I have done while writing that code.

Learning whether similar constructions appeared in the literature previously would require research of its own (I think most of it did not because the notion of a fiber sequence that does not use strict equality used in uu0a is, while obvious, probably new itself).

There is a lot of explanations in the first two videos of my Oxford lectures. See https://www.math.ias.edu/vladimir/lectures <https://www.math.ias.edu/vladimir/lectures>

Vladimir.

**Comment by nyraghu** [comment]
Thank you. I'll see those videos.
