### ISSUE TITLE
Should we minimize imports?

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#1664]
Jason Gross has a bug minimizer that aims to produce a minimal Coq file reproducing a given Coq error, using a brute-force approach.

Using a similar approach, we could try to minimize import statements in UniMath by deleting them, one by one, and see if the files still compile.

This could reduce the time it takes to recompile UniMath after changes to "early" files.

(Such an experiment would be done during the cold seasons, when the heat produced is useful for heating the home.)

**Comment by nmvdw** [comment]
I try to minimize imports except for Foundations/MoreFoundations, because to me, it is not always obvious which files in those directories are actually needed. I don't think that the benefits outweigh the costs for this.

**Comment by Kfwullaert** [comment]
> I try to minimize imports except for Foundations/MoreFoundations, because to me, it is not always obvious which files in those directories are actually needed. I don't think that the benefits outweigh the costs for this.

I also (try to) do the same. That I do is, is because I never really worked in the packages foundations and more foundations and therefore I don't really know the files. Furthermore, when trying to search for lemmas, it is easier to have them both entirely included as more results are found (again this is because I don't know in what files to look in those packages).

**Comment by m-lindgren** [comment]
There are probably optimizations to be done in the dependency graph that would involve not only removing unnecessary imports but also splitting some files into smaller ones, which would in theory also improve parallelization during the build process.

The challenge is that it's difficult to find the choke points and identify what material should be reorganized, because going at it blind risks causing more problems than it solves, and leave the library in a chaotic mess.

Related to this, generating the dependency graph and the producing a graphical presentation of the mathematical components and their connections would be a nice and not too time consuming task for a student with a little bit of scripting experience I think. (maybe there is a tool for this though)

**Comment by rmatthes** [comment]
> I try to minimize imports except for Foundations/MoreFoundations, because to me, it is not always obvious which files in those directories are actually needed. I don't think that the benefits outweigh the costs for this.

In `MoreFoundations.Tactics`, I profit from `show_id_type`, and this is not seen in the committed files. I am happy if this file is always imported (also for later experiments). Of course, there could be Emacs Lisp code to make toggling the presence of this import statement very easy.

**Comment by m-lindgren** [comment]
I always forget where `show_id_type` is defined and have to look for it. I would love to have it defined somewhere in Foundations (maybe easier to write on a post-it note that I put on my monitor).

**Comment by m-lindgren** [comment]
I put some more thought into this.

Minimizing imports using a script that only work on individual files, and test whether or not  the file compiles with a certain import removed, will remove imports it considers "unnecessary" because it does not take into account transitivity of imports. This can have the effect that files become less pleasant to work with, since identifiers can become long and complicated, while at the same time does nothing to improve the state of the dependency graph.

Example: `A` imports both `B` and `LongFileName`. `B` also imports `LongFileName`.

Suppose `A` does not mention any identifier defined in `LongFileName` but only uses the identifiers from `B` directly. The script will then determine that `LongFileName` is an unnecessary import, and remove it from `A`. This will however not improve the build at all, because the build order is still `LongFileName -> B -> A` just as before the change.

It will however possibly make it less pleasant to work in `A`, since you may see identifiers of the form `LongFileName.make_foo_object`. Importing `LongFileName` in `A` would give shorter identifiers to work with.

Another point to make following the above argument is that just because one of these scripts identifies an import as unnecessary does not mean that the author forgot to remove it or included too many by mistake, it's possible it actually filled a purpose.

It would be interesting to construct a script that removes imports that are _actually_ not necessary by taking into account the full dependency graph. Or even inspects `.vo` files to see if there is some import whose identifiers never occurs.

**Comment by peterlefanulumsdaine** [comment]
Following @m-lindgren ’s experiment, and others’ careful notes on it, I feel:

- I support minimising imports in general, to keep the dependency graph from being worse than necessary — in particular, generally avoiding `Package.All.` except with `Foundations` and `MoreFoundations`
- providing and promoting the script as a support tool for this seems very helpful
- on the other hand, there are often good reasons to keep a logically-redundant import, which the script can’t catch — so actually removing the apparently-redundant imports should only be done by hand, and with a bit of care

One easy thing to do here is to add a point in the style guide, encouraging authors to minimise imports, and documenting how the script can assist.

**Comment by arnoudvanderleer** [comment]
I think @peterlefanulumsdaine summarizes it nicely: minimize dependencies, but only for files that you are very familiar with.
I added an entry to [the wiki](https://github.com/UniMath/UniMath/wiki/Style-Guide). Is there anything else we want from this issue, or can I close it?
