### ISSUE TITLE
GrpdHITs currently not building over Coq dev

### ISSUE THREAD

**Issue by peterlefanulumsdaine** [UniMath/UniMath#1693]
Currently, the CI job “BuildGrpdHITs (Coq dev)” is consistently failing, see e.g. https://github.com/UniMath/UniMath/actions/runs/4971891863/jobs/8896730557?pr=1227

For those who know GrpdHITs better than me — is this something we should be looking to address here in UniMath, or that GrpdHITs should be fixing there?  It’d be good to have a clear path towards fixing the CI failure, somewhere.

**Comment by nmvdw** [comment]
Recently, in Coq dev there was a patch in Coq dev that affected private inductive types (https://github.com/coq/coq/pull/9609). GrpdHITs was affected by it, because it uses private inductive types to implement HITs. The fix is thus completely independent of stuff in UniMath, but it just is caused by this particular change. Coq might also have rewrite rules in the near future ('The Rewster: The Coq Proof Assistant with Rewrite Rules', https://types2023.webs.upv.es/Accepted.html), and that might give a better way of implementing HITs, so I am waiting with fixing it.

I think the best solution would be to temporarily remove the Coq dev check of GrpdHITs from the UniMath CI.

**Comment by peterlefanulumsdaine** [comment]
#1694 gives the short-term fix for this issue, but I suggest keeping the issue open (with slightly changed title), with the longer-term goal of adding GrpdHITs back in once they build again.

**Comment by nmvdw** [comment]
> @nmvdw This is resolved now, right?

Yes
