### ISSUE TITLE
which version of Coq are we allowed to use?

### ISSUE THREAD

**Issue by rmatthes** [UniMath/UniMath#1787]
I assume that pull requests may be done with code that contains new features of Coq 8.17.

In fact, the build on Mac OS is currently done with Coq 8.17.1 (even though the CI run has 8.16 in its title), the "latest" version on Ubuntu is Coq 8.18.0, and the development version is an alpha release of Coq 8.19.

**Comment by benediktahrens** [comment]
My opinion is that PRs should compile with the current release and with the development branch of Coq.

Maybe this is a discussion rather than an issue? Or do you want to point out that the CI instructions need updating?

**Comment by rmatthes** [comment]
So, there is an issue: Mac OS CI says 8.16 but is 8.17, while the current release is 8.18.

**Comment by arnoudvanderleer** [comment]
I agree with Benedikt. It makes sense to allow every feature in the last version of coq (modulo bugs, like for example in 8.20). If something breaks down in CI because of it, we should update the CI. Even if nothing breaks down, it is probably wise to keep the CI somewhat up-to-date.
And of course, it is good to have the CI also run with the development version of coq, because then we can spot problems with a new release before they really become a problem.

@rmatthes So the only actionable point in this issue is updating the MacOS CI, right?
