### ISSUE TITLE
Problem with notation in `AlgebraicTheories`?

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#1892]
```
File "./UniMath/AlgebraicTheories/LambdaTheories.v", line 227, characters 0-76:
Warning: Variable π does not occur in the right-hand side. The notation will
not be used for printing as it is not reversible.
[non-reversible-notation,parsing,default]
```

**Comment by arnoudvanderleer** [comment]
Ah. It works on my machine. These three lines are an attempt to make lambda terms a bit more readable. So `(a b)` instead of `app a b`, `λ' n, a` instead of `abs a` and `π i` instead of `var (make_stn _ i (idpath true))`. Especially the last one makes things a bit shorter (and hence, more readable). However, if it causes problems, we should at least improve this, or remove it altogether. What do you suggest?

**Comment by nmvdw** [comment]
It is a warning, right? So, it should compile, but it says that the notation won't be printed. What about adding ` : only parsing`? That should be semantically equivalent.

**Comment by arnoudvanderleer** [comment]
That would solve the warning. Although I added this notation mainly for printing :sweat_smile: 
I could not get most of this notation to work for parsing.

**Comment by nmvdw** [comment]
> That would solve the warning. Although I added this notation mainly for printing 😅

Sure. The warning does suggest that it is not printed, so it might be that with a different version/setup of Coq, it does not get printed. For this reason, it would be best to think of a better way to give this notation.

**Comment by arnoudvanderleer** [comment]
Indeed, I agree with you on that. I'll think of something. If I cannot think of something, I will remove the notation :-)
