### ISSUE TITLE
CI in trouble with Coq 8.21+alpha

### ISSUE THREAD

**Issue by rmatthes** [UniMath/UniMath#1896]
As of writing, Coq latest in our CI runs is still 8.19.1, but Coq dev jumped from 8.20 to 8.21+alpha.
The problems occur in the satellites TypeTheory and SetHITs.
This became manifest for PR #1891, see the discussion there.

**Comment by arnoudvanderleer** [comment]
The problem you are stating is not entirely clear to me. Can you please clarify whether
 - The version of coq in our CI is "wrong" or "outdated";
 - You'd like to add another version of coq to our CI, because the current versions are not sufficient in some sense;
 - You'd like someone to locally test UniMath on a coq version that is not in CI;
 - You'd like someone to fix the satellites to make sure that they work with a version of coq that is not in CI;
 - A combination of the above?

**Comment by rmatthes** [comment]
A rather quick fix was implemented in PR #1908 and improved in PR #1909. The PR that were merged afterwards triggered 17 CI runs each. The crucial element is that 8.20 is no longer the development version but not the latest version either. In this "limbo state", it was important to run CI with the release candidate, but preferably without hard-coding its name. Currently, 8.20 is hard-coded but at least not the release candidate ordinal. I consider the "limbo state" the one that has the highest risks of problems that should be reported to the Coq developers. For the satellites that do not pass the CI, the question was if the Coq developers wanted that behavior. I have not pursued this question.

**Comment by arnoudvanderleer** [comment]
Closing this, as it seems resolved. Feel free to reopen if you disagree.
