### ISSUE TITLE
Split up `DisplayedCats/Constructions.v`

### ISSUE THREAD

**Issue by arnoudvanderleer** [UniMath/UniMath#1922]
This is a large file which contains a lot of somewhat unrelated constructions. Some of these constructions have rather heavy prerequisites, which means that in order to use one construction, one has to compile a lot of files which have nothing to do with it. Also, recently I made an attempt to display-i-fy the construction of `(co)slicecat`, but using `disp_struct` from `Constructions.v` introduced a dependecy cycle:
```
   _build/default/UniMath/CategoryTheory/DisplayedCats/Constructions.vo
-> _build/default/UniMath/CategoryTheory/slicecat.vo
-> _build/default/UniMath/CategoryTheory/Subobjects.vo
-> _build/default/UniMath/CategoryTheory/SubobjectClassifier/SubobjectClassifier.vo
-> _build/default/UniMath/CategoryTheory/Categories/HSET/Structures.vo
-> _build/default/UniMath/CategoryTheory/Presheaf.vo
-> _build/default/UniMath/CategoryTheory/DisplayedCats/Fibrations.vo
-> _build/default/UniMath/CategoryTheory/DisplayedCats/Examples/Reindexing.vo
-> _build/default/UniMath/CategoryTheory/DisplayedCats/Constructions.vo
```
Therefore, want to propose to (partially) split up `Constructions.v` into files like `Constructions/DispStruct.v`. I would completely split up the file into coherent parts, and then leave `Constructions.v` with just a couple of export statements like `Require Export DisplayedCats/Constructions/DispStruct.v`, for backward compatibility.

**Comment by nmvdw** [comment]
There are numerous files in `DisplayedCats` that are quite large, and they mess up the dependency graph, and among them is `Constructions`. This has the following issues:
- It might cause unnecessary compilation. Sometimes I change a file and a large fragment of `Bicategories` needs to be rebuilt (I can't recall concrete examples).
- The potential for cyclic dependencies, as @arnoudvanderleer showed. 

The main disadvantage that splitting files brings, is that one might need to do much more imports. However, in this case, I don't think this will be problematic. The constructions that would be reused the most, are the full subcategory, product, and sigma, so it would only add 2 imports.

Overall, I am in favor of splitting up this file.

One thing that would be good to think about, is how we generally want to structure the `CategoryTheory` repository. Rather than finding an ad hoc solution for each problem we see on the way, it would be best if we have general guidelines/principles for when to split stuff into multiple files and where everything should be placed. However, this is a separate (but related) issue.

**Comment by arnoudvanderleer** [comment]
All right. Then I will split it up in the coming days.

Concerning more imports: I think I'll leave `Constructions.v` for backwards compatibility, so in most cases, one can either do 2 import statements, or just import the whole bunch together, like before.

Concerning a policy about splitting up files (and structuring `CategoryTheory`) it would be really nice to have that, but I also feel like it is impossible to capture the subtleties of such a complicated mathematics software development in a couple of rules. Although it might be possible to come up with a handful of "rules" for 80% of the cases.

**Comment by nmvdw** [comment]
> Concerning a policy about splitting up files (and structuring CategoryTheory) it would be really nice to have that, but I also feel like it is impossible to capture the subtleties of such a complicated mathematics software development in a couple of rules. Although it might be possible to come up with a handful of "rules" for 80% of the cases.

If the code is designed with a certain structure in mind, then this would already help a lot. It is not about having specific rules, it is about having a clear design in our directories and files.
