### ISSUE TITLE
Error when compiling with 8.19

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#1959]
I am getting this error with 8.19.1
```
File "./UniMath/CategoryTheory/MarkovCategories/Conditionals.v", line 115, characters 2-61:
Error: A left-recursive notation must have an explicit level.
```
Do you see the same?

**Comment by benediktahrens** [comment]
What level would be suitable? Should both notations have the same level?

**Comment by nmvdw** [comment]
They should be on the same level. I think level 0 might be fine (it compiles with that level).

Tagging @damast93

**Comment by damast93** [comment]
I don't have experience with levels, but I see no reason to not let it bind as tightly as possible, so 0 seems like a good choice. Also, left-associativity is desirable in the sense that `p|1|2` makes sense as `(p|1)|2` and not `p|(1|2)` which is meaningless, but maybe Coq does this automatically because this is a unary notation.
