### ISSUE TITLE
Inductive type bool from Coq's Init.Datatypes

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#197]
We are using the booleans of Coq.Init.Datatypes, which are defined as an inductive type:

```
Inductive bool : Set :=
  | true : bool
  | false : bool.
```

Should we try replacing it by unit \coprod unit?
Is the alternative definition of bool as coproduct already given somewhere?

**Comment by DanGrayson** [comment]
Before we do that, I'd like to try replacing ```coprod``` by ```total2``` over ```stn 2```.  Since many analogous theorems are proved for both ```coprod``` and ```total2```, we'd be able to shorten many proofs.  An example: a coproduct of sets is a set, and a total2 of a family of sets indexed by a set is a set.

**Comment by arnoudvanderleer** [comment]
@DanGrayson I think it would be unwise to define `coprod` via `total2`, because then we can no longer use the `induction` tactic for elements of `coprod A B` for case distinction.
And of course, we still could prove an induction principle lemma, but personally, I prefer being able to use the `induction` tactic.

**Comment by arnoudvanderleer** [comment]
Come to think of it, we have the same problem with `coprod unit unit`, because then `induction x` will give two cases: `inl x'` and `inr x'`. These are not definitionally equal to `true` and `false`, not everything in `unit` is definitionally equal to `tt`. So we would have to do `induction x as [x' x']; induction x'.` or something like that. And that feels cumbersome when one neesd to to it very often.
So is this a thing we still want?

**Comment by arnoudvanderleer** [comment]
On the other hand, it may be possible to write a tactic that can apply an induction principle lemma for some custom types. Something like
```coq
Tactic old_induction = induction.

Tactic induction [some parameter x] :=
  match typeof x with
    coprod => refine (coprod_ind _ _)
    bool => refine (bool_ind _ _)
    _ => induction x
  end.
```

**Comment by arnoudvanderleer** [comment]
Oh, I just realized that we can provide our own induction principles to coq with `induction ... using some_bool_rect`, so it is slightly more of a hassle, but still doable.

Regardless, @benediktahrens , how does this tie into the freeze of Foundations?

**Comment by arnoudvanderleer** [comment]
Closing this as no longer relevant. Feel free to reopen if there is still interest in having/doing this.
