### ISSUE TITLE
make clean should rm user-contrib/UniMath

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#215]

**Comment by DanGrayson** [comment]
Maybe not, for two reasons:

1) the tradition is that when a software package is built and installed, the cleaning operation does
not include uninstallation.  That's because the purpose of installation is to enable further use.

2) in future, the user will be using Coq as distributed by INRIA, not the Coq in sub/coq, so we won't
necessarily know where the files got installed by it.
