### ISSUE TITLE
Re-integrate the homs-are-sets assumption in the definition of precategory; make inverses compute better

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#362]
I suggest the following changes to the CategoryTheory library:
1. The homs-are-sets assumption should be re-integrated into the definition of precategories.
2. The definition of isomorphism should be the "normal" one.

The first point should be rather trivial to solve. The second one requires more coding, but not too much either, since in practice one often resorts to working with the normal definition anyway.

The current definitions have several inconveniences:
1. Extra arguments of type `has_homsets ...` have to be given to functions, making the code more difficult to read
2. We lose convertibility when computing the inverse of an isomorphism, see, e.g., #279 . Another example is the fact that 'taking inverse' and 'taking pointwise iso' of a natural isomorphism do not commute up to convertibility.

The current definitions have few advantages:
1. We do not, to my knowledge, have an example of a precategory that does not have hom-sets.
2. We do not have a lot of interesting constructions that do not require the homs-are-sets condition.

**Comment by DanGrayson** [comment]
I'd be in favor of this.

Here's an example of a precategory without hom-sets: the category of small types, where the arrows
are the functions.

**Comment by JasonGross** [comment]
I'm curious why 2 is related to the separation of the homset argument.  What can you do with it that you can't do without?

**Comment by benediktahrens** [comment]
On 06/12/2016 05:46 PM, Jason Gross wrote:
> I'm curious why 2 is related to the separation of the homset
> argument.  What can you do with it that you can't do without?

The usual definition of isomorphism, called "is_z_iso" in UniMath, is
the right one only for Precategories (i.e., for precategories whose
hom-types are sets):
only for Precategories is "is_z_iso(f)" a proposition.

The current definition of "is_iso(f)" is a proposition also for
precategories, but it lacks some definitional equalities that one has
for z_isos.

**Comment by vladimirias** [comment]
Maybe this will work:

1. precategory - no assumptions on the h-levels of objets or morphisms. Examples: types and functions, a type and paths in it, precategory of precategories, categories etc.

2. category - a precategory with morphism types being sets.

3. setcategory - a category with the object type being a set.

4. univ_precategory - a precategory such that the functions from paths to isomorphisms (as currently defined) are equivalences.

5. univ_category - same with morphism types being sets.

To this we add coercions 5 -> 4 -> 1, 5 -> 2 , 3 -> 2 -> 1 and in theorems use concepts with minimal requirements.

Vladimir.

**Comment by benediktahrens** [comment]
On 06/13/2016 01:34 PM, Vladimir Voevodsky wrote:
> Maybe this will work:
> 
> 1. precategory - no assumptions on the h-levels of objets or
> morphisms. Examples: types and functions, a type and paths in it,
> precategory of precategories, categories etc.
> 
> 2. category - a precategory with morphism types being sets.
> 
> 3. setcategory - a category with the object type being a set.
> 
> 4. univ_precategory - a precategory such that the functions from
> paths to isomorphisms (as currently defined) are equivalences.

It is the current definition of isomorphism that suffers from some
annoying defects.

My main goal is to go back to the normal definition of isomorphism, and
re-integrating the homs-are-sets assumption is just a prerequisite for
that, not my main goal.

**Comment by vladimirias** [comment]
What if you make the function from the current definition to the usual definition a coercion?

**Comment by DanGrayson** [comment]
Coq can issue annoying warning messages about ambiguous coercions, so it might be good to avoid a scheme like this:

"To this we add coercions 5 -> 4 -> 1, 5 -> 2 , 3 -> 2 -> 1 and in theorems use concepts with minimal requirements."

**Comment by vladimirias** [comment]
Annoying warnings should not stop us from making the coercions that we need. We already have many of those in algebra and they do not cause any real trouble.

**Comment by benediktahrens** [comment]
On 06/13/2016 04:50 PM, Vladimir Voevodsky wrote:
> What if you make the function from the current definition to the
> usual definition a coercion?

I don't see how inserting another function will give more convertibility.

**Comment by vladimirias** [comment]
Could you say more specifically what convertibility you need and in what context?

**Comment by benediktahrens** [comment]
On 06/13/2016 08:34 PM, Vladimir Voevodsky wrote:
> Could you say more specifically what convertibility you need and in what context?

One example is given in issue #279 [1]:

there, the inverse of an isomorphism built giving f, g and proofs that f
and g are inverse to each other does not reduce to g.
Instead, to prove that the inverse of f is g, one needs to apply id_right.


Another example arises when considering natural isomorphisms:
Given a natural isomorphism i,
i^{-1}(x) is not convertible to (i(x))^{-1}.
Again, to show that they are equal, we need to apply id_right.
The current proof of that equality is unnecessarily complex, see [2],
applying id_right would do the job. But it should not necessitate a
proof at all.


This lack of convertibility becomes annoying in the theory of displayed
categories, where we consider types of arrows indexed by arrows in the
base category.


[1] https://github.com/UniMath/UniMath/issues/279

[2]
https://github.com/UniMath/UniMath/blob/master/UniMath/CategoryTheory/functor_categories.v#L985

**Comment by mortberg** [comment]
I agree with Benedikt here. It would be nice to have a name for categories with hom *sets* and I have also had some trouble with the notion of iso. It seems like everyone agree that we should introduce a name for categories with hom sets, but that it is not clear what to do with the isos. How about I first implement Vladimir's suggestion for structure and we then figure out what to do with the isos?

**Comment by vladimirias** [comment]
(Also posted to Univalent Mathematics) *About the naming of categories (cf. issue #362 in UniMath).*

In the theory of infty-categories, (infty,1)-categories with hom-sets are called 1-categories or (1,1)-categories. 

We currently call them Precategories. I do not like the current name since it is completely non-descriptive. It is, however, easy to replace with anything else.  Our current "precategories" are (infty,1)-categories with only one layer of associativity and identity conditions imposed (and without the univalence condition). 

We recently extended "assoc" etc. to binary operations on general types. We will soon have assoc and assoc2 (the pentagon). The latter will be used for example in the definition of monoidal categories (attn. @AnthonyBordg). 

We will soon have (infty,2)-categories as precategories with additional structure - among which will be the the analogs of the assoc2 for multi-object composition. 

The levels/layers in the concept of a general (infty,infty)-category are complicated.

a. There is, firstly, how many levels there are of morphism types that are different of the equality types.  For that we should have a number d, including infty - (infty,0)-category has  0 levels, that is, it is simply a type. (infty,1)-category has 1 level, (infty,2) has 2-levels etc. 

b. There is, secondly, how high an h-level may have the types of objects and the types of morphisms on each level where they can be different from equalities. For objects which, I think, people in the set-theoretic maths call (infty,d)-category it is a sequence of (d+1) numbers (l_0,...,l_d) where (2,...,2) corresponds to a d-category where objects and morphisms of all levels form sets. 

To comply with the convention of the set-theoretic maths we should write the length of the sequence after the sequence itself. 

So we should have a number d, including infty, and a list of d+1 numbers, also including infty. For example, the type of the ((2,0),1)-categories is equivalent to the type of sets with monoidal operation. As set-theoretic maths suggest, the type of the ((2,0,...,0),d)-categories for d>1 is, independently from d, equivalent to the type of sets with a commutative monoidal operation.

c. There is, thirdly, how many levels of the associativity and the left and right unity conditions as well as mixed associativities are added for each composition. The combinatorics of this part of the structure I do not yet know. 

Going back to Precategories and ignoring for now the unsolved problem (c) we see that they should be called ((infty,2),1)-categories. Indeed, no restriction on the type of objects is imposed (infty), types of morphisms are sets (2) and there is only one level of morphism types where they differ from the identity types (1).  

For now, until a solution for (c) is found Precategories is fine to me.

**Comment by vladimirias** [comment]
Since @benediktahrens started or starting to work on my original proposal about naming I re-iterate that I prefer "categories" to "Precategories".

**Comment by vladimirias** [comment]
BTW I plan to work on a PR extending my last one by introducing "typewithbinop"and re-definiting setwithbinop as a typewithbinop together with "isaset" component. Most results about setwithbinop (and twobinop) extend to typewithbinop verbatim. Where needed one can add isaset as an extra parameter. 

This will simplify a number of proofs where the problem is that sets, being pairs and not types, do not have elements and what is worse they can not be a source or a target of a coercion. For example, the following does not compile:

Definition test : natset -> nat := idfun _. 
Coercion test : natset >-> nat . 

It will address the analog of issue #700 at the level of sets.

**Comment by DanGrayson** [comment]
Changing "Precategory" to "category" is fine with me.

**Comment by peterlefanulumsdaine** [comment]
This old issue is now fully resolved following #1402 and #1507 , I think?

**Comment by benediktahrens** [comment]
Yes, closing.
