### ISSUE TITLE
Moving contents from Ktheory.Utilities to Foundations

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#365]
The module Ktheory.Utilities has many useful lemmas, in particular about transport. They would be even more useful if they were in a more canonical place, such as Basics.PartX.
Any volunteers for moving them there?

**Comment by DanGrayson** [comment]
Sure, I can do it.  The summer is about to finally "begin" for me tomorrow.

**Comment by benediktahrens** [comment]
At the moment, there is also this in Utilities:
```
Axiom PostponedProof : empty.
Ltac postponeProof := apply fromempty, PostponedProof.
```
Is there an advantage of this custom tactic over the `admit.` tactic?
The `admit.`tactic has the advantage that it only allows `Admitted.` and `Abort.` at the end of a proof, thus making the status of the proof clear.

**Comment by DanGrayson** [comment]
I guess not, since I didn't use it even once.

**Comment by benediktahrens** [comment]
Also, Cathy uses stuff from 

- UniMath/Ktheory/Tactics
- UniMath/Ktheory/Utilities
- UniMath/Ktheory/QuotientSet

in her Topology, in particular she uses `Sequence`.

Could that go somewhere in Basics, too?

**Comment by DanGrayson** [comment]
Okay.

**Comment by benediktahrens** [comment]
There is some stuff about categories that would be good to have in CT instead of Ktheory, see, e.g., discussion in #502 .
To keep #502 tractable, let's defer this to later, but not too much later.

**Comment by DanGrayson** [comment]
Closing, see https://github.com/UniMath/UniMath/pull/592#issuecomment-281873412

**Comment by benediktahrens** [comment]
On 02/23/2017 04:10 AM, Daniel R. Grayson wrote:
> Closing, see https://github.com/UniMath/UniMath/pull/592#issuecomment-281873412

Instead of closing this issue, I vote for renaming it into "... to
Auxiliary", for a package "Auxiliary" (or whatever) still to be created.

**Comment by DanGrayson** [comment]
Okay, I'll reopen it again when it's ready to be reconsidered.

"Auxiliary" is perhaps not so good, since it conveys the impression that the items within are not needed.  "Basics" is free, but that might confuse the history of the project.  I suggest "Miscellany" tentatively.  That conveys the idea that the items within don't fit into one of the other categories, and its position as the second item in the list of packages conveys the idea that the items within are supposed be useful to subsequent packages, which we can also say in the README.

What about a location for miscellaneous items that are interesting but not useful for other packages?  We might want a folder called something like "AuxiliaryMaterial" or "MoreMiscellany" at the end of the list of packages.

By the way, the package "Tactics" contains 5 files of Warren's that could/should be moved into the package under discussion.  Perhaps then someone one will try to use them.

**Comment by vladimirias** [comment]
I still suggest Foundations_0, Foundations_1, which we may want to lock too some time in the future, and Foundations_3 will be introduced and will become the open package for additions to the foundational stuff.

> Miscellany
> 
is a good name for the stuff that does not have a good place in the structured part of the library.

**Comment by DanGrayson** [comment]
Re: " Foundations_0, Foundations_1, Foundations_3 "

Nondescript numbers convey no meaning to the reader; indeed, I can't guess what distinction you have in mind between the first two.  And if they are all part of a larger entity called "Foundations", it would be good to preserve "Foundations" as a package and put those three things inside it as subdirectories.

Meanwhile I submitted a pull request using "Preliminaries", but don't care whether the name is changed in the future.

**Comment by vladimirias** [comment]
I had in mind Foundations_0 as my original foundations updated only as necessary and edited for pedagogical purposes.

Foundations_1 as what we will start creating now. We may think, for example, of starting by repeating the structure of Foundations_0 and placing in the corresponding files what we would like to place in the files of Foundations_0 with the same names. Later we may restructure Foundations_1 without restructuring Foundations_0 and they will diverge.

Eventually, Foundations_2 may be created if we decide to restrict access to Foundations_1.

Vladimir.

**Comment by DanGrayson** [comment]
The current Foundations has already diverged a lot from the original, and I
don't see a good way to get the
original foundations except by copying it in from a past version: we could
make a copy, put it in a new package
called OriginalFoundations at the top of the list, and make sure it works.

Using the same structure and file names in the two Foundations would not be
good, since we had good reasons for creating the packages NumberSystems,
Combinatorics, Algebra, etc., and we might want to keep improving the
structure, as well as the filenames.  For example, eventually the names
PartA .. PartD should be replaced by something meaningful.

**Comment by benediktahrens** [comment]
Why don't we create a separate repository

UniMath/Foundations

in which the original Foundations library is maintained?

It might also be easy to update vladimirias/Foundations to the latest Coq.


I dislike the idea of having related material scattered over different
files.
While understanding Vladimir's wish to maintain an untampered copy of
his work, I think, this would best be done outside UniMath/UniMath.

**Comment by DanGrayson** [comment]
That's a good proposal, too.  There is a conflict between maintaining the past and constructing the future.  Once Foundations_0 diverges sufficiently from Foundations_1, the pedagogical value of having something smaller and older to look at may be negated by the pedagogical necessity of looking also at the new before one can start contributing.

**Comment by vladimirias** [comment]
I disagree. Doing it in the way that you suggest will lead to the accumulation of divergence between the “original Foundations” and the Foundations used in the UniMath. That will make learning original Foundations useless for the understanding of the basics of the UniMath. Instead one will have to learn the “new Foundations” that, and this is the main reason for the locking idea, I expect to become filled with many useful. but inessential results and

** becoming an encyclopedia instead of a book **

I want to have the main Foundation that I will make into a very readable book with many comments, references and elegant mathematical structure and that will be locked because a book has to be written by one or at most a fixed number of authors and a book like that may take many years to make.

Foundations_1 will then be an encyclopedia that can be understood by reading it from any place and that will contain many useful results that did not get into the Foundation_0 because they were not necessary for the understanding of the rest of the material in the Foundations_0.

Note, that when I say ‘a book’, I don’t mean a book such as the Hott-book but a book such as the better volumes of Bourbaki are or, maybe, something even more whole and based not on compromises, but on a vision.

And, it is very important that the UniMath is based directly on this book so that a student who has read it can then read the encyclopedia that comes with it (Foundations_1) and the rest of the UniMath. 

Vladimir.

**Comment by DanGrayson** [comment]
Re: "Doing it in the way that you suggest will lead to the accumulation of divergence between the “original Foundations” and the Foundations used in the UniMath. That will make learning original Foundations useless for the understanding of the basics of the UniMath. Instead one will have to learn the “new Foundations” that, and this is the main reason for the locking idea ..."

Indeed, that's exactly what I said, except that the divergence has already happened, and if we follow your proposal to prevent improvements to the most basic parts, or to undo the improvements that have already happened, the divergence will increase and continue as improved versions of things in Foundations_0 get deposited in Foundations_1 under the same names (which was your suggestion).

The idea of the first parts of the system having pedagogical value as a book instead of an encyclopedia for the rest is an excellent one, but the best way to achieve it might be to forget the historical record and to edit the files PartA-D as they exist today with an eye toward creation of the "book".  I would find that fun to do, and I know how to streamline code to get to results efficiently.  Even the Preamble is cluttered with stuff inessential for learning, such as the definition of the tactic "use".

Think of it as the "essential Foundations" instead of the "original Foundations".

**Comment by DanGrayson** [comment]
... that even suggests the name:
```
PACKAGES += EssentialFoundations
PACKAGES += Foundations
PACKAGES += Combinatorics
PACKAGES += Algebra
PACKAGES += NumberSystems
PACKAGES += CategoryTheory
PACKAGES += Ktheory
PACKAGES += Topology
PACKAGES += RealNumbers
PACKAGES += Tactics
PACKAGES += SubstitutionSystems
PACKAGES += Folds
PACKAGES += HomologicalAlgebra
```

**Comment by vladimirias** [comment]
I a combination of what Benedikt suggests — "original Foundations" as a separate repo that we will keep up to date with the Coq changes, and what you suggest “essential Foundations” that will be minimalistic and book-like and Foundations that will be encyclopedia-like, sounds good to me.

However, I would like to request in addition that, unlike with the rest of the UniMath, which is kind of meritocratic, the work on the essential Foundations will be a monarchy with me at the head.

**Comment by DanGrayson** [comment]
That proposal is okay with me.  Others.

I'd be happy to initialize your monarchy with about fifty lines of essential code in a new package called "EssentialFoundations", if you wish.  That way you wouldn't have to futz with file organization issues at the very beginning.

**Comment by vladimirias** [comment]
Yes, please! Generally, the monarch is not the one who does all the work… :)

**Comment by DanGrayson** [comment]
:-)

**Comment by DanGrayson** [comment]
Benedikt, do you like the idea?

**Comment by benediktahrens** [comment]
On 02/25/2017 09:26 PM, Daniel R. Grayson wrote:
> Benedikt, do you like the idea?

Yes!
