### ISSUE TITLE
Not to use the implication symbol for morphisms in a category

### ISSUE THREAD

**Issue by vladimirias** [UniMath/UniMath#429]
Please, we must not use the implication symbol, from logic, for morphisms in a category! We should use it for himpl and not reuse it unless necessary.

The old notation --> was easy to type and very clear. Why mess up something that works when we have so much real work to do?

**Comment by benediktahrens** [comment]
On 08/20/2016 02:54 PM, Vladimir Voevodsky wrote:
> Please, we must not use the implication symbol, from logic, for
> morphisms in a category! We should use it for himpl and not reuse it
> unless necessary.
> 
> The old notation --> was easy to type and very clear. Why mess up
> something that works when we have so much real work to do?

This notation is not used for morphisms in a category in UniMath.
Its uses are:

- In Folds for "folds morphisms" of various kinds. However, that usage
is only local to the corresponding files. The notation is not exported
when importing the contents of those files.

- In Ktheory it is used as follows:

UniMath/Ktheory/Precategories.v:Notation "c ⇒ X" := (arrow c X)  (at
level 50) : cat. (* \r= *)


If necessary, I can remove the usage of ⇒ from the Folds package.


Probably you are referring to the use of this arrow in a different
library. In that library, it should indeed be changed.

**Comment by vladimirias** [comment]
Sorry, if I caused unnecessary alarm. It was the result of reading Peter Lumsdaine’s “record” formulation of “displayed categories” in the ahrens-lumsdaine-voevodsky repo. which is not not a part of the UniMath. I just assumed, wrongly, that it was taken from the UniMath.

**Comment by DanGrayson** [comment]
I also use a long ascii double arrow to denote the type of functors between two categories in Ktheory:
```
Notation "a ==> b" := (functor a b) (at level 50) : cat.
```
I imagine we can't use `=>` for a notation because it would conflict with Coq's notation `fun ... => ...`.

It turns out that `himpl` is almost unused in the Foundations: just in the lemma `hconjtohdisj`.

Our current Unicode notation for it is both local and confined to a scope:
```
Local Notation "A ⇒ B" := (himpl A B) (at level 95, no associativity) : logic.
```
I put it in a scope and made it local because it is used so seldom, and others might want to use it for something else in other contexts.
