### ISSUE TITLE
Towards Coq 8.6

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#514]
Coq 8.6rc1 was announced today, see [1] for a list of changes.
We should check that UniMath works with 8.6, if possible before the official release of 8.6.
I have tried compiling UniMath with 8.6rc1, encountering the following error: 
```
COQC UniMath/Foundations/Algebra/Apartness.v
File "./UniMath/Foundations/Algebra/Apartness.v", line 63, characters 0-36:
Error: Options "simpl never" and "!" are incompatible.
build/CoqMakefile.make:465: recipe for target 'UniMath/Foundations/Algebra/Apartness.vo' failed
make: *** [UniMath/Foundations/Algebra/Apartness.vo] Error 1
```
The error message is clear: one cannot combine ! and `simpl never`.
I don't mind submitting a fix, but I am not sure how to fix this particular problem.
It works to remove `!X`, but I cannot exclude that that change has undesired consequences, such as making the goal unreadable or similar.

[1] http://coq.inria.fr/coq-86

**Comment by benediktahrens** [comment]
Another issue I have encountered is in the proof of `accth` in file `StandardFiniteSets.v`.
The proof stops working in Coq8.6rc1. To repair it, it suffices to remove all the `simpl.` in the proof.
The problem is, I think, that when calling `simpl', a proof of `isaprop` is thrown away and cannot be reconstituted when executing
```
set ( j := natlehchoice2 _ _ ( pr1 is'' ) ).
```
The problem seems to be, if I understand correctly, that `natlehchoice2` takes an argument of type `n \le m`, which itself is defined as an hProp, instead of an argument of the type underlying the hProp `n \le m`.
It is the proof of the fact that `n \le m` is an hProp that is thrown away by `simpl.` and that cannot be reconstructed in the above `set...`.

**Comment by benediktahrens** [comment]
The last culprit I have encountered is the need to fill in the missing argument in UniMath/Foundations/NumberSystems/NaturalNumbers.v in
```
Definition negnatlehsn0 (n : nat) : ¬ (S n ≤ 0) := negnatlthn0 _.
```

Other than that, UniMath compiles fine with Coq 8.6rc1.

I suggest we don't fix these issues right now, but instead check to what extent they are still present in rc2 and in the released version of 8.6.

**Comment by DanGrayson** [comment]
I suggest fixing them now, for then you don't have to remember the fixes.

On Dec 9, 2016 7:43 AM, "Benedikt Ahrens" <notifications@github.com> wrote:

The last culprit I have encountered is the need to fill in the missing
argument in UniMath/Foundations/NumberSystems/NaturalNumbers.v in

Definition negnatlehsn0 (n : nat) : ¬ (S n ≤ 0) := negnatlthn0 _.

Other than that, UniMath compiles fine with Coq 8.6rc1.

I suggest we don't fix these issues right now, but instead check to what
extent they are still present in rc2 and in the released version of 8.6.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_UniMath_UniMath_issues_514-23issuecomment-2D266016578&d=DQMFaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=PAZ_jTPLrSb1btCfAu4RkycWe57N0sGyzbjgeOn2wN0&m=U8iVMU5Jq2clDnypH4gfqGSk_ZjrU0Qna08Q6IPKN6k&s=9sU10geQRmqWSr-Bv-C7TbUB4DYqGKSX0U4u13csCIU&e=>,
or mute the thread
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAqvRD-5FvWbl6ZlBvVMVw3ebdl7fROA0Fks5rGVrwgaJpZM4LIEt2&d=DQMFaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=PAZ_jTPLrSb1btCfAu4RkycWe57N0sGyzbjgeOn2wN0&m=U8iVMU5Jq2clDnypH4gfqGSk_ZjrU0Qna08Q6IPKN6k&s=tPvs3pD9PxAhF0Yl_F9wJUP_d2ceHCR4IzxZ8zY0bRE&e=>
.

**Comment by benediktahrens** [comment]
One of the issues is that
```
Arguments EOge_rel {!X} x y: simpl never.
```
is not accepted any more in Coq 8.6
I have replaced it by
```
Arguments EOge_rel : simpl never.
```
and similarly elsewhere.

I would like to understand the choice for the former, which ceases to be accepted in Coq8.6, before doing this change.

**Comment by DanGrayson** [comment]
8.6 is out now: https://coq.inria.fr/news/134.html

Shall I take a look?

**Comment by JasonGross** [comment]
> It works to remove `!X`, but I cannot exclude that that change has undesired consequences

I am not sure what you were aiming for in 8.5, but whatever it was, your arguments list did not achieve it.  The modifier `simpl never` means "don't unfold when running `simpl`", and the modifier `!` means "only unfold if the argument in this position begins with a constructor".  I think the 8.5 behavior is to discard the latter when the former is passed, but there's no sensible meaning you can give to the combination that you don't get from passing only one of them.

**Comment by benediktahrens** [comment]
On 12/15/2016 01:38 AM, Daniel R. Grayson wrote:
> 8.6 is out now: https://coq.inria.fr/news/134.html
> 
> Shall I take a look?

Yes, thanks a lot. 
I documented all the issues I encountered, and the solutions I found, in this issue. There weren't many, anyway.

**Comment by DanGrayson** [comment]
Re:
```
Error: Options "simpl never" and "!" are incompatible.
```
It seems clear that removing the "!" is an innocent fix.
