### ISSUE TITLE
duality in category theory

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#602]
A lot of our category theory code is doubled in size because notions and their duals get separate definitions and proofs.  Is there a way to economize?

More specifically, is ElementsOp needed?  If so, can its statements be corollaries of those in Elements?  The file is used here: https://github.com/mweav/UniMath/blob/elems-slice-equiv/UniMath/CategoryTheory/elems_slice_equiv.v

See Anders' comment here: https://github.com/UniMath/UniMath/pull/590#issuecomment-281938037

**Comment by mortberg** [comment]
An issue that we have is that C^op^op is not judgmentally the same as C. I suspect that this is one of the reasons for the problems we had when dualizing statements about limits. A solution to this problem is to define categories as in the HoTT library:

https://github.com/HoTT/HoTT/blob/master/theories/Categories/Category/Core.v#L58

As you see a category comes with two proofs of associativity and op'ing a category just swaps the two proofs, hence one gets C^op^op=C judgmentally. Mathematically this is not so nice, but maybe it's a trick which is worthwhile to implement?

Note that in cubicaltt we don't have this problem as symmetry is an involution (i.e. `<i> p @ -i @ -i = <i> p @ i` judgmentally) and we get C^op^op=C for the standard definition of category:

https://github.com/mortberg/cubicaltt/blob/master/examples/opposite.ctt

**Comment by DanGrayson** [comment]
Re: "one gets C^op^op=C judgmentally"

That would be wonderful, but it's only with primitive projections turned on, which still don't work for us.  I was working on that yesterday...

**Comment by benediktahrens** [comment]
On 02/23/2017 02:36 PM, Anders Mörtberg wrote:
> An issue that we have is that C^op^op is not judgmentally the same as
> C. I suspect that this is one of the reasons for the problems we had
> when dualizing statements about limits. A solution to this problem is
> to define categories as in the HoTT library:
> 
> https://github.com/HoTT/HoTT/blob/master/theories/Categories/Category/Core.v#L58
>
>  As you see a category comes with two proofs of associativity and
> op'ing a category just swaps the two proofs, hence one gets C^op^op=C
> judgmentally. Mathematically this is not so nice, but maybe it's a
> trick which is worthwhile to implement?
> 
> Note that in cubicaltt we don't have this problem as symmetry is an
> involution (i.e. `<i> p @ -i @ -i = <i> p @ i` judgmentally) and we
> get C^op^op=C for the standard definition of category:
> 
> https://github.com/mortberg/cubicaltt/blob/master/examples/opposite.ctt

I don't remember this to be a big problem. I think that we should not
use implementation tricks at the price of obscuring our mathematics.

I remember that one problem we had was too much unfolding (that has been
mentioned already), so that, e.g., constructing a pullback suddenly
became constructing a pushout in the opposite category.

I think that writing an interface for the envisioned "definitions by
opp-ing" will require as much work as manually dualizing statements and
proofs. It will certainly require a careful use of the `Opaque` and
`simpl never` directives.

**Comment by mortberg** [comment]
We actually kept the attempt to define limits in terms of colimits in the opposite category in a separate module:

https://github.com/UniMath/UniMath/blob/master/UniMath/CategoryTheory/limits/graphs/limits.v#L538

It looks like for easy things it worked pretty well, but for more complicated results (e.g. limits lift to functor categories) we had to more or less as much work as for the analogous result for colimits. To resolve this issue and to understand what the problem is this file is probably a good place to start.

**Comment by vladimirias** [comment]
I think we should even consider the possibility of having separate definitions of a covariant and a contravariant functor with a lot of parallel constructions.

**Comment by vladimirias** [comment]
This is an issue that deserves further thinking. Any idea that will give us (C^{op})^{op}=C substitutionally deserves our attention and experiments.

**Comment by JasonGross** [comment]
You don't need to turn on primitive projections globally; either use `Record` for your categories and locally set primitive projections, or make an alternate form of `total2` that supports judgmental eta.

I'd be curious to know, in any case, what's stopping you from turning on primitive projections globally?

Also, even when you have `(Cᵒᵖ)ᵒᵖ` judgmentally equal to `C`, make sure not to define limits and colimits via Kan extensions; if you do, you will still run into trouble, because `(1 → C)ᵒᵖ` is not judgmentally the same as `1 → Cᵒᵖ` (though I have two [feature](https://coq.inria.fr/bugs/show_bug.cgi?id=5291) [requests](https://coq.inria.fr/bugs/show_bug.cgi?id=5293) open that will, I hope, allow this to be the case; if you're using `total2` for everything, then you should only need the first of these, which requests a unit type with judgmental eta).

**Comment by DanGrayson** [comment]
Re: "I'd be curious to know, in any case, what's stopping you from turning on primitive projections globally?"

Some of our proofs stop working.  The latest one is in Ktheory/AffineLine.v.

**Comment by DanGrayson** [comment]
Let's revive this issue a bit and discuss making C^op^op=C work judgmentally, which
we can do, now that primitive projections have been turned on.  See https://github.com/UniMath/UniMath/pull/669#issuecomment-291086220.

The question to be decided, experimentally, is whether a lot of code is simplified.  For example, can ElementsOp.v be removed?  I bet it can.

**Comment by siddharthist** [comment]
[Here's the link](https://github.com/HoTT/HoTT/blob/19e6cbbee21da50c2c532eb8a4988be14e935d99/theories/Categories/Category/Core.v#L58-L63) to how it works in HoTT/HoTT. To summarize, they define a category as having symmetric proofs of equality:
```
      associativity : forall x1 x2 x3 x4
                             (m1 : morphism x1 x2)
                             (m2 : morphism x2 x3)
                             (m3 : morphism x3 x4),
(m3 o m2) o m1 = m3 o (m2 o m1);
      (** Ask for the symmetrized version of [associativity], so that [(Cᵒᵖ)ᵒᵖ] and [C] are equal without [Funext] *)
      associativity_sym : forall x1 x2 x3 x4
                                 (m1 : morphism x1 x2)
                                 (m2 : morphism x2 x3)
                                 (m3 : morphism x3 x4),
m3 o (m2 o m1) = (m3 o m2) o m1;
```
And then have a "constructor" so you don't have to provide both proofs:
```coq

(** Define a convenience wrapper for building a precategory without
    specifying the redundant proofs. *)
Definition Build_PreCategory
           object morphism identity compose
           associativity left_identity right_identity
  := @Build_PreCategory'
       object
       morphism
       identity
       compose
       associativity
       (fun _ _ _ _ _ _ _ => symmetry _ _ (associativity _ _ _ _ _ _ _))
       left_identity
       right_identity
(fun _ => left_identity _ _ _).
```

**Comment by DanGrayson** [comment]
Right, that's what we have in mind.
