### ISSUE TITLE
Change notation for functors and natural transformations to make them ressemble 2-categorical notation

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#620]
as per https://github.com/UniMath/UniMath/pull/613#issuecomment-282545442

One solution would simply be to swap the notations, but we can also think about a unicode variant of `==>`.

**Comment by DanGrayson** [comment]
Could you show us the corresponding characters or definitions?

**Comment by benediktahrens** [comment]
On 02/26/2017 01:20 PM, Daniel R. Grayson wrote:
> Could you show us the corresponding characters or definitions?
> 

From functor_categories.v :

```
Notation "a ==> b" := (functor a b) (at level 50) : cat.
Notation "F ⟶ G" := (nat_trans F G) (at level 39) : cat.
```

**Comment by DanGrayson** [comment]
Your idea is good and I like ⟶ and ⟹ .

Why are the levels different?

**Comment by rmatthes** [comment]
The higher the cell level in the n-category, the higher the number of horizontal lines.

**Comment by DanGrayson** [comment]
I meant the parsing levels, 39 and 50.

**Comment by rmatthes** [comment]
Sorry.

**Comment by DanGrayson** [comment]
Shall we agree to make it ⟶ and ⟹?  I could do it and figure out a suitable parsing level for them to share.

**Comment by mortberg** [comment]
How does one type these? It would be nice if it was \-> and \=>

**Comment by benediktahrens** [comment]
On 02/28/2017 01:18 PM, Daniel R. Grayson wrote:
> Shall we agree to make it ⟶ and ⟹?  I could do it and figure out a suitable parsing level for them to share.

That would be great. The arrows are good.

**Comment by DanGrayson** [comment]
It's \--> for ⟶ and I will make \==> give ⟹.  The shorter ones you suggest are already  in use 
for short arrows : → ⇒ .

**Comment by mortberg** [comment]
Ok, that sounds great

**Comment by DanGrayson** [comment]
The font `-*-STIXGeneral-normal-normal-normal-*-12-*-*-*-p-0-iso10646-1 (#x6AE)` displays the arrows this way:

<img width="97" alt="screen shot 2017-02-28 at 8 22 13 am" src="https://cloud.githubusercontent.com/assets/700228/23406883/2c5236a8-fd8f-11e6-98d9-e071df458c8e.png">

and the font `-Misc-Fixed-normal-normal-normal-*-15-*-*-*-c-90-iso10646-1` displays them this way:

<img width="93" alt="screen shot 2017-02-28 at 8 22 21 am" src="https://cloud.githubusercontent.com/assets/700228/23406891/33ce7e28-fd8f-11e6-87ba-2f41371c56aa.png">

**Comment by mortberg** [comment]
That is unfortunate. I use the font Inconsolata-g (http://leonardo-m.livejournal.com/77079.html), I wonder how the are displayed there. 

Maybe using ascii (--> and ==>) would be safer?

**Comment by benediktahrens** [comment]
On 02/28/2017 02:31 PM, Anders Mörtberg wrote:
> That is unfortunate. I use the font Inconsolata-g
> (http://leonardo-m.livejournal.com/77079.html), I wonder how the are
> displayed there.
> 
> Maybe using ascii (--> and ==>) would be safer?
> 

The arrow "-->" is already used for other stuff, namely hom-types in a
precategory.

**Comment by DanGrayson** [comment]
Yes, it's unfortunate, and dealing with fonts always gives me a headache, but we should not make our decision based on bad fonts lurking out there.  Using a different font is a manageable problem, which we can solve.

**Comment by DanGrayson** [comment]
Since you use  Inconsolata-g , can you show us how they look in it?

**Comment by mortberg** [comment]
I know that "-->" is for hom-types, but I don't like that notation as it hides the category so I would be in favor of getting rid of it. 

About fonts and unicode. I agree that it is annoying and something that gives a headache. But using tons of unicode notations for things that we can do in ascii not only gives troubles with various fonts but also when writing emails or comments on github (Yes I could configure my browser somehow so that I can type all these symbols, but I'm too lazy). That's why I really like for example the notations "(x : A) -> B" for pi types and "(x : A) * B" for sigma types.

Oh wait, I'm only using Inconsolata-g on my laptop. In my office I use Sans Regular, this is what \\--> and \\==> looks like on my office machine:

⟶
  ≡>

Not very nice... :\

**Comment by mortberg** [comment]
Actually it seems like \\==> didn't work and that it is \\== followed by >...

**Comment by DanGrayson** [comment]
Yes, that's why I said I will have to make it work.  I just add a line to .dir-locals.el.

**Comment by mortberg** [comment]
Ok, never mind my stupid copy-paste above. I can of course not just do that, I have to take a screenshot and send it. Anyway if it doesn't work with my font I'll find another one. But my remark about unicode still remains, I think using fancy unicode symbols is a lot of hassle for very little gain.

**Comment by DanGrayson** [comment]
Hiding the category with `a-->b` can be a good thing, especially if the category takes a lot of space to display.  Maybe what's needed is a way to switch back and forth easily.  Or do we already have that?

Also `a-->b` is useful for input.

**Comment by DanGrayson** [comment]
I think I couldn't even have stated these lemmas without the right notation, and unicode makes them ever so much more beautiful:

<img width="652" alt="screen shot 2017-02-28 at 8 56 51 am" src="https://cloud.githubusercontent.com/assets/700228/23407871/efcf7768-fd93-11e6-9c8f-0337f5cd37cd.png">

**Comment by mortberg** [comment]
If the category is complicated but inferrable I usually write `_[[a,b]]` instead of `a --> b`.

Haha, looking at that code makes me think you would like Agda. There you can even use any unicode symbols in your identifiers.

**Comment by DanGrayson** [comment]
Well, for input, each user can type what they prefer.  Arrows are standard mathematical notation for morphisms in a category, and we should cater to standard practice.

**Comment by rmatthes** [comment]
I reviewed several papers on Agda developments, and my feeling was that this creates unpronounceable mathematics and computer science. Japanese researchers would probably not care so much since they are accustomed to that for proper names. Western tradition was that you could also read the stuff to others, in principle. One channel less for transmission is a risk. Did you consider the package Company-Coq for ProofGeneral that would allow to beautify ASCII symbols? So, with Company-Coq turned on, one would see nice symbols, but the sources would still be communicated in the simple forms we know. I have no deep experience with it, though.

**Comment by DanGrayson** [comment]
I wonder what you're referring to with the word "this".

**Comment by DanGrayson** [comment]
I'm in favor of simplicity, too, but I think Unicode can accommodate simplicity, especially if we use standard mathematical practice as a guide.  I think we should trust our authors and the reviewers of our pull requests.

**Comment by rmatthes** [comment]
@DanGrayson: "this" rather referred to what Anders was describing: that in Agda, you can use Unicode abundantly in identifiers as well; and my review experience was that of abundant use. This possibility is exciting and frightening alike, and it reminds me (of stories I read but that were confirmed by real people) of Japanese having to send a fax to their business partners to tell their name since a description of the Chinese symbols used in their names would have been too awkward - pronouncing the name was totally insufficient.

**Comment by DanGrayson** [comment]
I think we do have some files already where abundant unicode in identifiers occurs.  I don't think we'll have to read those files to someone else over the telephone, though, and the files look pretty, at least to me.

Having a system as you suggest where what we see on the screen does not agree with what's in the file seems hazardous and confusing.
