### ISSUE TITLE
Optimization in Coq when Kernel Term Sharing is disabled

### ISSUE THREAD

**Issue by mortberg** [UniMath/UniMath#680]
This is not really an issue, but I just want to point your attention to:

https://github.com/coq/coq/pull/555

Maybe @ppedrot can elaborate what he means by "UniMath which abuses the flag"?

**Comment by ppedrot** [comment]
My take on the current situation is that the kernel by-need reduction is broken. Not in the sense it is unsound, but rather because I think it has not been conceived with the same goals in mind at the time (i.e. reduction vs conversion). I've convinced myself of this by repeated profiling of what it was doing.

UniMath pokes right where it hurts, to the point it has to deactivate sharing. Don't misunderstand me, I know this is the only thing you can do. But it is a mere workaround, and the real issue is still there.

**Comment by DanGrayson** [comment]
Wow, how do you count CPU cycles and CPU instructions?

**Comment by mortberg** [comment]
Thanks for the clarification @ppedrot. 

@DanGrayson: I suspect they are using perf: https://perf.wiki.kernel.org/

**Comment by rmatthes** [comment]
After discussion in Nantes with @ppedrot, I have asked the Coq developers to document the option we are using : [Issue 6164](https://github.com/coq/coq/issues/6164). In addition, we could document how we use it in UniMath and when one should consider trying it out for a given proof task.

**Comment by benediktahrens** [comment]
This issue seems to be resolved, closing.
