### ISSUE TITLE
some files print needlessly

### ISSUE THREAD

**Issue by DanGrayson** [UniMath/UniMath#773]
```
COQC UniMath/CategoryTheory/Inductives/Lists.v
     = 0
     : nat
     = 2
     : nat
     = 2
     : nat
     = 7
     : nat
     = 9
     : nat
     = 4
     : nat
     = 16
     : nat
     = 2,, 5,, 2,, tt
     : list (pr1 natHSET)
COQC UniMath/CategoryTheory/Inductives/Trees.v
     = 11
     : nat
     = 11
     : nat
```

**Comment by benediktahrens** [comment]
Additionally, we had put in some commands producing output in files of
the SubstitutionSystems package. This was in order to avoid a timeout of
Travis, triggered when there is no output for 10 minutes.

In the meantime, Travis, Coq, and UniMath have become better, and maybe
those commands can be removed as well.
