### ISSUE TITLE
Rename rng to ring

### ISSUE THREAD

**Issue by siddharthist** [UniMath/UniMath#822]
Some use the term "rng" to refer to [non-unital rings](https://en.wikipedia.org/wiki/Rng_(algebra)). Shortening to rng would be confusing without this fact, and is misleading considering it.

**Comment by DanGrayson** [comment]
It would have been nice if Vladimir had used `Ring` instead of `rng` -- now it's probably too late for a change.

The notion of ring with unit is unimportant, and this is the first I've heard of "rng" being used as a name for such things.  I think there shouldn't be a name for such things.

I propose we leave things as they are.

**Comment by benediktahrens** [comment]
Should this issue be closed?

**Comment by DanGrayson** [comment]
No, now I think we should change it.  I remark that "rng" is not used in Foundations, and there is a wikipedia page for "rng" here: https://en.wikipedia.org/wiki/Rng_(algebra)
