### ISSUE TITLE
On the definition of BinDirectSums (biproducts)

### ISSUE THREAD

**Issue by mortberg** [UniMath/UniMath#823]
Why does the definition of a biproduct have these five extra conditions: https://github.com/UniMath/UniMath/blob/master/UniMath/CategoryTheory/limits/BinDirectSums.v#L34 ? I don't think they are usually required for biproducts?

Also, wouldn't it be better to just take a precategory instead of a PreAdditive category?

Maybe @tpannila can explain why the assumptions are what they are.

**Comment by DanGrayson** [comment]
That's strange.  The usual way to do it is to say that 3 objects with 4 maps and 5 equations like that form a direct sum diagram, and then to prove that the existence of such a thing based on 2 given objects is equivalent to binary products and binary coproducts existing and being isomorphic to each other.  That's the way I started to do it in `Ktheory/DirectSums`, but for n objects instead of for 2.

One definitely needs a pre-additive category in order to be able to write the equations, which involve such things as "0" and "+".

**Comment by mortberg** [comment]
I was thinking that one can define it as for an arbitrary precategory: https://en.wikipedia.org/wiki/Biproduct#Definition

One can then prove what you say in the special case of PreAdditive category

**Comment by peterlefanulumsdaine** [comment]
I’ve seen it both ways round in the literature — either definition taken as primitive, and the other then given as an equivalent form.

Since the product/coproduct definition can be stated in greater generality, it seems more natural to me take that as the main definition.  But either way, I agree we should give *one* of the two standard definitions, rather than a mixture of the two as it seems we currently do (unless we are missing someting and @tpannila had a deliberate reason for this).

**Comment by DanGrayson** [comment]
Oops, I wasn't paying close attention to the original post.  Those equations seem to be needed, and the definition given at https://en.wikipedia.org/wiki/Biproduct#Definition seems wrong, because there are no equations relating the projections and the inclusions.  Without the equations, the definition amounts to saying that the given objects have a product and a coproduct, and the product object and the coproduct object are equal to each other.  It can't ever be right to assert baldly that two objects of a category are equal to each other.

**Comment by tpannila** [comment]
Hi,

When I formalized BinDirectSums, my goal was to formalize homological algebra. In particular, I
didn't aim for maximal generality. If one wants to study biproducts in arbitrary categories, one
can split the definition into 2 parts.

Can you give examples of categories which have biproducts, but are not preadditive?




About the equations. (I have not verified these)

The idea behind the equations is that they give a way to construct/factorize the unique
morphisms to/from the biproducts from/to morphisms between components, and not just use the unique
existence property for limits.

More precisely. Suppose you have morphism ``f : x -> y`` and ``g : z -> w``. Then the unique morphism
``x \oplus z -> y \oplus w`` is given by, something like,
``pr1 \circ f \circ in1 + pr2 \circ g \circ in2``.

Also, if we have ``f : x -> y , h : y -> z`` and ``g : a -> b, k : b -> c``, then the unique morphism is
given by ``pr1 \circ f \circ h \circ in1 + in2 \circ g \circ k \circ pr2``.

Also, if you have an arbitrary morphism ``ff : x \oplus y -> z \oplus w``. Then you can factor it to
components
``
ff = pr1 \circ (in1 \circ ff \circ pr1) \circ in1 +
     pr2 \circ (in2 \circ ff \circ pr2) \circ in2.
``
Where the morphism in brackets are ``x -> z and y -> w``.


By using induction, and properties of addition of morphisms, one should be able to informally
generalize these to all finite biproducts so that the order in which the sum is taken does not
matter.



With kind regards,

Tomi

**Comment by arnoudvanderleer** [comment]
@mortberg Is there anything more that you would want out of this issue than Tomi's answer?

**Comment by mortberg** [comment]
> @mortberg Is there anything more that you would want out of this issue than Tomi's answer?

No, I think it answered it, so I'll close the issue
