### ISSUE TITLE
Compilation broken with Coq master (8.8)

### ISSUE THREAD

**Issue by SkySkimmer** [UniMath/UniMath#921]
See eg https://gitlab.com/SkySkimmer/coq/-/jobs/54189808
Broken by 2ce2885a356024ba409aef6b9d77d44d6843aede

**Comment by DanGrayson** [comment]
Oops.  I know why this is -- since we no longer include the makefile built by coq_makefile, we no longer get the definition of VDFILE that we use for determining whether we are being built with 8.7 or 8.8, which affects the way we get the *.v.d files built, so we need another way to test the version of Coq.  Perhaps we should grep the created makefile for VDFILE.

Or maybe there is a version-independent way to get the *.v.d files built...

Maybe our travis build should have one more build step where we build against a different version of coq, so we can track compatibility with two versions of Coq simultaneously.

I'll have a fix later today.

**Comment by DanGrayson** [comment]
Let me know of that fixes it!

**Comment by Zimmi48** [comment]
I'm under the impression that it is still broken as of today. See this build trace on a branch that should not be breaking UniMath: https://travis-ci.org/Zimmi48/coq/jobs/346805521

**Comment by DanGrayson** [comment]
Thanks!

**Comment by DanGrayson** [comment]
Okay, now I hope that should fix it, let me know!

**Comment by Zimmi48** [comment]
Yes, it's working again. Thanks!
