### ISSUE TITLE
Activate all warnings

### ISSUE THREAD

**Issue by benediktahrens** [UniMath/UniMath#968]
We should activate all warnings, to be motivated to keep our code in good shape. Currently, we have
```
-w '-notation-overridden,-local-declaration,+uniform-inheritance,-deprecated-option'
```
We should replace that by
```
-w all
```

**Comment by arnoudvanderleer** [comment]
@benediktahrens @rmatthes What is the status of this? Do we still want this, and if so, has it been done yet?

**Comment by rmatthes** [comment]
@arnoudvanderleer This issue seems to refer to the makefile, the current situation being https://github.com/UniMath/UniMath/blob/master/Makefile#L110, with the only warning flag `-notation-overridden`. For Dune, the settings are similar: https://github.com/UniMath/UniMath/blob/master/UniMath/dune#L12.
Changing only the makefile would not make any sense. It would certainly be worth a try to see if the number of warnings becomes untractable when showing all of them.

**Comment by arnoudvanderleer** [comment]
I did a quick test, and the result does not seem to be intractable, but there is still some inflation.
```
        coqc UniMath/CategoryTheory/GrothendieckConstruction/Projection.{glob,vo}
File "./UniMath/CategoryTheory/GrothendieckConstruction/Projection.v", line 18, characters 0-43:
Warning: Notation "_ ≠ _" was already used in scope nat_scope.
[notation-overridden,parsing,default]
File "./UniMath/CategoryTheory/GrothendieckConstruction/Projection.v", line 18, characters 0-43:
Warning: Notation "_ ≠ _" was already used in scope nat_scope.
[notation-overridden,parsing,default]
        coqc UniMath/Induction/PolynomialFunctors.{glob,vo}
        coqc UniMath/CategoryTheory/Chains/CoAdamek.{glob,vo}
        coqc UniMath/CategoryTheory/DisplayedCats/Binproducts.{glob,vo}
File "./UniMath/CategoryTheory/DisplayedCats/Binproducts.v", line 18, characters 0-43:
Warning: Notation "_ ≠ _" was already used in scope nat_scope.
[notation-overridden,parsing,default]
File "./UniMath/CategoryTheory/DisplayedCats/Binproducts.v", line 18, characters 0-43:
Warning: Notation "_ ≠ _" was already used in scope nat_scope.
[notation-overridden,parsing,default]
        coqc UniMath/Bicategories/Core/AdjointUnique.{glob,vo}
File "./UniMath/Bicategories/Core/AdjointUnique.v", line 11, characters 0-43:
Warning: Notation "_ ≠ _" was already used in scope nat_scope.
[notation-overridden,parsing,default]
File "./UniMath/Bicategories/Core/AdjointUnique.v", line 11, characters 0-43:
Warning: Notation "_ ≠ _" was already used in scope nat_scope.
[notation-overridden,parsing,default]
        coqc UniMath/CategoryTheory/Limits/Coends.{glob,vo}
File "./UniMath/CategoryTheory/Limits/Coends.v", line 19, characters 0-43:
Warning: Notation "_ ≠ _" was already used in scope nat_scope.
[notation-overridden,parsing,default]
File "./UniMath/CategoryTheory/Limits/Coends.v", line 19, characters 0-43:
Warning: Notation "_ ≠ _" was already used in scope nat_scope.
[notation-overridden,parsing,default]
        coqc UniMath/CategoryTheory/Limits/Cokernels.{glob,vo}
        coqc UniMath/CategoryTheory/Limits/Graphs/Coequalizers.{glob,vo}
        coqc UniMath/CategoryTheory/Limits/Pushouts.{glob,vo}
```

**Comment by rmatthes** [comment]
Yes, warnings of this kind abound. In my last partial compilation with Dune, I compiled 1263 files, with only 150 warnings according to the current settings. With all warnings activated, another partial compilation with Dune of 896 files had 1238 warnings, with 1185 having the substring "was already used". This means there should be an issue concerning this recurrent warning and no change to the warning settings (otherwise, who would still look into the warnings?).

**Comment by arnoudvanderleer** [comment]
Okay, so what are you proposing? Closing this issue and creating a new one about this recurrent warning?

**Comment by rmatthes** [comment]
This would be optimal - to my mind.

**Comment by arnoudvanderleer** [comment]
Closing this issue then
